In [3]:
import pandas as pd
import cloudscraper
from datetime import datetime, timedelta, date
from dateutil.relativedelta import relativedelta
import boto3
from io import BytesIO
import time
import random
import json

BUCKET_NAME = "afdal-idx-stock-data-s3"
METADATA_KEY = "metadata/etl_control.json"

In [47]:
def read_df_from_s3(bucket_name, key):
    s3 = boto3.client("s3")
    response = s3.get_object(
        Bucket=bucket_name,
        Key=key
    )
    buffer = BytesIO(response["Body"].read())
    return pd.read_parquet(buffer)

In [3]:
def get_month_list(start_date, end_date):
    months = set()
    current_date = start_date
    while current_date <= end_date:
        year = current_date.year
        month = current_date.month
        year_month = year * 100 + month
        months.add(year_month)
        current_date += timedelta(days=1)
    return sorted(months)

In [5]:
def load_raw(start_date, end_date):
    months = get_month_list(start_date, end_date)
    s3 = boto3.client("s3")

    dfs = {}
    for i, month in enumerate(months):
        mm = f'{month%100:02d}'
        yyyy = f'{int(month/100)}'
        # print(f'{mm}-{yyyy},{i}')
        if i!=len(months)-1:
            key = f'raw/idx/year={yyyy}/month={mm}/data.parquet'
            dfs[key] = read_df_from_s3(BUCKET_NAME, key)
        else:
            first_date = f'{yyyy}-{mm}-01' if len(months)>1 else f'{start_date}'
            list_date = pd.date_range(first_date, f'{end_date}')
            for j in list_date:
                date = j.date()
                key = f'raw/idx/year={yyyy}/month={mm}/daily/date={date}/data.parquet'
                dfs[key] = read_df_from_s3(BUCKET_NAME, key)

    return dfs

In [58]:
star_date = datetime.strptime('2026-08-30', '%Y-%m-%d').date()
end_date = datetime.strptime('2026-09-01', '%Y-%m-%d').date()
dfs = load_raw(star_date, end_date)
# print(1)

In [7]:
standarize_column_name ={
    "IDStockSummary" : "stock_summary_id",
    "Date" : "trade_date",
    "StockCode" : "stock_code",
    "StockName" : "stock_name",
    "Remarks" : "remarks",
    "DelistingDate" : "delisting_date",
    "Previous" : "previous_price",
    "OpenPrice" : "open_price",
    "FirstTrade" : "first_trade_price",
    "High" : "high_price",
    "Low" : "low_price",
    "Close" : "close_price",
    "Change" : "price_change",
    "Volume" : "volume",
    "Value" : "trading_value",
    "Frequency" : "frequency",
    "IndexIndividual" : "individual_index",
    "Offer" : "offer_price",
    "OfferVolume" : "offer_volume",
    "Bid": "bid_price",
    "BidVolume": "bid_volume",
    "ListedShares": "listed_shares",
    "TradebleShares": "tradeable_shares",
    "WeightForIndex": "index_weight",
    "ForeignSell": "foreign_sell",
    "ForeignBuy": "foreign_buy",
    "NonRegularVolume": "non_regular_volume",
    "NonRegularValue": "non_regular_value",
    "NonRegularFrequency": "non_regular_frequency",
}

In [92]:
df = dfs['raw/idx/year=2026/month=08/data.parquet']
df.head()

,No,stock_summary_id,trade_date,stock_code,stock_name,remarks,previous_price,open_price,first_trade_price,high_price,...,tradeable_shares,index_weight,foreign_sell,foreign_buy,delisting_date,non_regular_volume,non_regular_value,non_regular_frequency,persen,percentage
0,1,4065341,2026-08-03,AADI,Adaro Andalan Indonesia Tbk.,--MO1SD0F10000A121------------,9225.0,9300.0,9300.0,9300.0,...,7786891760,1.498977e+09,2396100,503600,NaT,147964,1.339833e+09,16,None,None
1,2,4065342,2026-08-03,AALI,Astra Agro Lestari Tbk.,--MO113E100000D232------------,6875.0,6900.0,6900.0,7175.0,...,1924688333,3.903268e+08,1111300,738100,NaT,0,0.000000e+00,0,None,None
2,3,4065343,2026-08-03,ABBA,Mahaka Media Tbk.,--U-4100000000E614-E---------X,30.0,0.0,0.0,0.0,...,3935892857,1.298451e+09,0,0,NaT,0,0.000000e+00,0,None,None
3,4,4065344,2026-08-03,ABDA,Asuransi Bina Dana Arta Tbk.,--UO2105000000G412------------,3500.0,0.0,0.0,3530.0,...,620806680,5.947328e+07,0,0,NaT,0,0.000000e+00,0,None,None
4,5,4065345,2026-08-03,ABMM,ABM Investama Tbk.,--MO1135000000A121------------,2510.0,2550.0,2550.0,2580.0,...,2753165000,4.129748e+08,14600,197600,NaT,16200,4.357800e+07,1,None,None

In [9]:
def rename_column(dataframe):
    dataframe.rename(columns=standarize_column_name, inplace=True)
    return dataframe

In [1]:
df = rename_column(dfs['raw/idx/year=2026/month=08/data.parquet'])
df.head(10)

NameError: name 'rename_column' is not defined

In [69]:
integer_columns = [
    "stock_summary_id",
    "volume",
    "frequency",
    "offer_volume",
    "bid_volume",
    "listed_shares",
    "tradeable_shares",
    "foreign_sell",
    "foreign_buy",
    "non_regular_volume",
    "non_regular_frequency",
]

float_columns = [
    "previous_price",
    "open_price",
    "first_trade_price",
    "high_price",
    "low_price",
    "close_price",
    "price_change",
    "trading_value",
    "individual_index",
    "offer_price",
    "bid_price",
    "index_weight",
    "non_regular_value",
]

string_columns = [
    "stock_code",
    "stock_name",
    "remarks",
]

date_columns = [
    "trade_date",
    "delisting_date",
]


def cast_datatype(dataframe):
    # Integer
    for column in integer_columns:
        dataframe[column] = pd.to_numeric(
            dataframe[column],
            errors="coerce"
        ).astype("Int64")

    # Float
    for column in float_columns:
        dataframe[column] = pd.to_numeric(
            dataframe[column],
            errors="coerce"
        ).astype("float64")

    # String
    for column in string_columns:
        dataframe[column] = dataframe[column].astype("string")

    # Date
    for column in date_columns:
        dataframe[column] = pd.to_datetime(
            dataframe[column],
            errors="coerce"
        ).dt.date

    return dataframe

In [85]:
def quality_check(dataframe):
    errors = []

    # 1. Cleaning awal: Ubah nilai negatif/sentinel (< 0) jadi NaN untuk kolom numerik
    non_negative_columns = [
        "previous_price", "open_price", "first_trade_price", "high_price",
        "low_price", "close_price", "volume", "trading_value", "frequency",
        "offer_price", "offer_volume", "bid_price", "bid_volume",
        "listed_shares", "tradeable_shares", "foreign_sell", "foreign_buy",
        "non_regular_volume", "non_regular_value", "non_regular_frequency",
    ]

    for col in non_negative_columns:
        if col in dataframe.columns:
            invalid_count = (dataframe[col] < 0).sum()
            if invalid_count > 0:
                logging.warning(f"Warning: {invalid_count} baris bernilai < 0 pada kolom '{col}' diubah menjadi NaN.")
                dataframe.loc[dataframe[col] < 0, col] = np.nan

    # 2. Required / NOT NULL check (Fatal Error)
    required_columns = ["trade_date", "stock_code"]
    null_columns = dataframe[required_columns].isna().any()
    if null_columns.any():
        columns = null_columns[null_columns].index.tolist()
        errors.append(f"NULL ditemukan pada required column: {columns}")

    # 3. Duplicate check (Fatal Error)
    duplicate_mask = dataframe.duplicated(subset=required_columns, keep=False)
    if duplicate_mask.any():
        errors.append(
            f"Terdapat duplikat berdasarkan ({required_columns[0]}, {required_columns[1]}): {duplicate_mask.sum()} rows"
        )

    # 4. OHLC validation (Setelah dibersihkan jadi NaN, validasi ini otomatis aman dari angka negatif)
    ohlc_validations = {
        "High < Low": dataframe["high_price"] < dataframe["low_price"],
        "Open < Low": dataframe["open_price"] < dataframe["low_price"],
        "Open > High": dataframe["open_price"] > dataframe["high_price"],
        "Close < Low": dataframe["close_price"] < dataframe["low_price"],
        "Close > High": dataframe["close_price"] > dataframe["high_price"],
    }

    for rule, invalid_mask in ohlc_validations.items():
        if invalid_mask.any():
            #Warning anomali
            logging.warning(f"OHLC Warning - {rule}: {invalid_mask.sum()} rows terdeteksi anomali (kemungkinan saham FCA).")

    # 5. Trade date future check (Fatal Error)
    future_date_mask = dataframe["trade_date"] > pd.Timestamp.today().date()
    if future_date_mask.any():
        errors.append(f"trade_date berada di masa depan: {future_date_mask.sum()} rows")

    # Final result
    if errors:
        raise ValueError(
            "Quality check failed (Structural Error):\n- "
            + "\n- ".join(errors)
        )

    print("Quality check passed")
    return dataframe

In [86]:
df = quality_check(df)

WARNING:root:OHLC Warning - Open < Low: 3768 rows terdeteksi anomali (kemungkinan saham FCA).
WARNING:root:OHLC Warning - Close > High: 2472 rows terdeteksi anomali (kemungkinan saham FCA).

Quality check passed

In [ ]:

# %%
import logging
from io import BytesIO
from datetime import datetime, timedelta, date

import boto3
import numpy as np
import pandas as pd

BUCKET_NAME = "afdal-idx-stock-data-s3"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

logger = logging.getLogger(__name__)

#Mapping column
STANDARDIZE_COLUMN_MAP = {
    "IDStockSummary": "stock_summary_id",
    "Date": "trade_date",
    "StockCode": "stock_code",
    "StockName": "stock_name",
    "Remarks": "remarks",
    "DelistingDate": "delisting_date",

    "Previous": "previous_price",
    "OpenPrice": "open_price",
    "FirstTrade": "first_trade_price",
    "High": "high_price",
    "Low": "low_price",
    "Close": "close_price",
    "Change": "price_change",

    "Volume": "volume",
    "Value": "trading_value",
    "Frequency": "frequency",

    "IndexIndividual": "individual_index",

    "Offer": "offer_price",
    "OfferVolume": "offer_volume",
    "Bid": "bid_price",
    "BidVolume": "bid_volume",

    "ListedShares": "listed_shares",
    "TradebleShares": "tradeable_shares",
    "WeightForIndex": "index_weight",

    "ForeignSell": "foreign_sell",
    "ForeignBuy": "foreign_buy",

    "NonRegularVolume": "non_regular_volume",
    "NonRegularValue": "non_regular_value",
    "NonRegularFrequency": "non_regular_frequency",
}


EXPECTED_SOURCE_COLUMNS = set(STANDARDIZE_COLUMN_MAP.keys())

EXPECTED_CURATED_COLUMNS = list(STANDARDIZE_COLUMN_MAP.values())


# Data type
INTEGER_COLUMNS = [
    "stock_summary_id",
    "volume",
    "frequency",
    "offer_volume",
    "bid_volume",
    "listed_shares",
    "tradeable_shares",
    "foreign_sell",
    "foreign_buy",
    "non_regular_volume",
    "non_regular_frequency",
]

FLOAT_COLUMNS = [
    "previous_price",
    "open_price",
    "first_trade_price",
    "high_price",
    "low_price",
    "close_price",
    "price_change",
    "trading_value",
    "individual_index",
    "offer_price",
    "bid_price",
    "index_weight",
    "non_regular_value",
]

STRING_COLUMNS = [
    "stock_code",
    "stock_name",
    "remarks",
]

DATE_COLUMNS = [
    "trade_date",
    "delisting_date",
]


# S3
def read_df_from_s3(bucket_name, key):

    s3_client = boto3.client("s3")

    response = s3_client.get_object(
        Bucket=bucket_name,
        Key=key
    )

    buffer = BytesIO(response["Body"].read())

    return pd.read_parquet(buffer)

def get_month_list(start_date, end_date):
    months = set()

    current_date = start_date

    while current_date <= end_date:
        year_month = current_date.year * 100 + current_date.month
        months.add(year_month)

        current_date += timedelta(days=1)

    return sorted(months)


def load_raw(start_date, end_date):
    months = get_month_list(start_date, end_date)

    s3 = boto3.client("s3")

    dfs = {}

    for i, year_month in enumerate(months):

        month = year_month % 100
        year = year_month // 100

        mm = f"{month:02d}"
        yyyy = f"{year:04d}"


        if i != len(months) - 1:
            key = f"raw/idx/year={yyyy}/month={mm}/data.parquet"

            logger.info(f"Loading raw: {key}")

            dfs[key] = read_df_from_s3(BUCKET_NAME, key)

        else:
            if len(months) > 1:
                first_date = date(year, month, 1)
            else:
                first_date = start_date

            date_range = pd.date_range(
                first_date,
                end_date
            )

            for current_date in date_range:
                current_date = current_date.date()
                key = f"raw/idx/year={yyyy}/month={mm}/daily/date={current_date}/data.parquet"

                logger.info(f"Loading raw: {key}")

                dfs[key] = read_df_from_s3(BUCKET_NAME,key)

    logger.info(f"Loaded {len(dfs)} raw files")

    return dfs


# Validation
def validate_source_schema(dataframe):
    actual_columns = set(dataframe.columns)

    missing_columns = EXPECTED_SOURCE_COLUMNS - actual_columns
    unexpected_columns = actual_columns - EXPECTED_SOURCE_COLUMNS

    if missing_columns:
        raise ValueError(
            f"Source schema validation failed. Missing columns: {sorted(missing_columns)}"
        )

    if unexpected_columns:
        logger.warning(
            f"Unexpected source columns detected: {sorted(unexpected_columns)}"
        )

    logger.info("Source schema validation passed")

    return dataframe


# Rename columns
def rename_columns(dataframe):
    return dataframe.rename(
        columns=STANDARDIZE_COLUMN_MAP
    )


# Data type casting
def cast_numeric_column(dataframe, column, dtype):
    original = dataframe[column]

    original_null = original.isna()

    converted = pd.to_numeric(
        original,
        errors="coerce"
    )

    conversion_error_mask = (
        ~original_null &
        converted.isna()
    )

    conversion_error_count = conversion_error_mask.sum()

    if conversion_error_count > 0:

        bad_values = original[
            conversion_error_mask
        ].unique()

        raise ValueError(
            f"Datatype conversion failed for column "
            f"'{column}'. "
            f"{conversion_error_count} invalid values. "
            f"Examples: {bad_values[:5]}"
        )

    dataframe[column] = converted.astype(dtype)

    return dataframe


def cast_datatypes(dataframe):
    """
    Apply the curated data type contract.
    """

    # --------------------------------------------------------
    # Integer
    # --------------------------------------------------------

    for column in INTEGER_COLUMNS:

        dataframe = cast_numeric_column(
            dataframe,
            column,
            "Int64"
        )

    # --------------------------------------------------------
    # Float
    # --------------------------------------------------------

    for column in FLOAT_COLUMNS:

        dataframe = cast_numeric_column(
            dataframe,
            column,
            "float64"
        )

    # --------------------------------------------------------
    # String
    # --------------------------------------------------------

    for column in STRING_COLUMNS:

        dataframe[column] = (
            dataframe[column]
            .astype("string")
            .str.strip()
        )

    # --------------------------------------------------------
    # Date / datetime
    # --------------------------------------------------------

    for column in DATE_COLUMNS:

        dataframe[column] = pd.to_datetime(
            dataframe[column],
            errors="coerce"
        ).dt.date

    logger.info("Datatype casting passed")

    return dataframe


# ============================================================
# DATA QUALITY CHECK
# ============================================================

def quality_check(dataframe):
    errors = []

    # ========================================================
    # 1. Required columns
    # ========================================================

    required_columns = [
        "trade_date",
        "stock_code",
    ]

    for column in required_columns:

        if dataframe[column].isna().any():

            count = dataframe[column].isna().sum()

            errors.append(
                f"NULL found in required column "
                f"'{column}': {count} rows"
            )

    # ========================================================
    # 2. Required string values must not be empty
    # ========================================================

    empty_stock_code = (
        dataframe["stock_code"]
        .fillna("")
        .str.strip()
        .eq("")
    )

    if empty_stock_code.any():

        count = empty_stock_code.sum()

        errors.append(
            f"Empty stock_code: {count} rows"
        )

    # ========================================================
    # 3. Duplicate grain
    # ========================================================

    grain_columns = [
        "trade_date",
        "stock_code",
    ]

    duplicate_mask = dataframe.duplicated(
        subset=grain_columns,
        keep=False
    )

    if duplicate_mask.any():

        duplicate_count = duplicate_mask.sum()

        errors.append(
            f"Duplicate grain detected for "
            f"({', '.join(grain_columns)}): "
            f"{duplicate_count} rows"
        )

    # ========================================================
    # 4. Non-negative values
    #
    # IDX uses negative sentinel values such as -9999999
    # for fields that cannot logically be negative.
    #
    # Treat them as NULL.
    # ========================================================

    non_negative_columns = [
        "previous_price",
        "open_price",
        "first_trade_price",
        "high_price",
        "low_price",
        "close_price",

        "volume",
        "trading_value",
        "frequency",

        "offer_price",
        "offer_volume",
        "bid_price",
        "bid_volume",

        "listed_shares",
        "tradeable_shares",

        "foreign_sell",
        "foreign_buy",

        "non_regular_volume",
        "non_regular_value",
        "non_regular_frequency",
    ]

    for column in non_negative_columns:

        invalid_mask = dataframe[column] < 0

        if invalid_mask.any():

            count = invalid_mask.sum()

            logger.warning(
                f"Negative sentinel values detected in "
                f"'{column}': {count} rows. "
                f"Converting to NULL."
            )

            dataframe.loc[
                invalid_mask,
                column
            ] = pd.NA

    # ========================================================
    # 5. OHLC consistency
    # ========================================================

    ohlc_validations = {

        "High < Low":
            dataframe["high_price"] <
            dataframe["low_price"],

        "Open < Low":
            dataframe["open_price"] <
            dataframe["low_price"],

        "Open > High":
            dataframe["open_price"] >
            dataframe["high_price"],

        "Close < Low":
            dataframe["close_price"] <
            dataframe["low_price"],

        "Close > High":
            dataframe["close_price"] >
            dataframe["high_price"],
    }

    for rule, invalid_mask in ohlc_validations.items():

        count = invalid_mask.sum()

        if count > 0:

            logger.warning(
                f"OHLC anomaly - {rule}: "
                f"{count} rows"
            )

    # ========================================================
    # 6. Future trade date
    # ========================================================

    today = pd.Timestamp.today().date

    future_date_mask = (
        dataframe["trade_date"] > today
    )

    if future_date_mask.any():

        count = future_date_mask.sum()

        errors.append(
            f"trade_date in the future: "
            f"{count} rows"
        )

    # ========================================================
    # 7. Final result
    # ========================================================

    if errors:

        raise ValueError(
            "Quality check failed:\n- "
            + "\n- ".join(errors)
        )

    logger.info("Quality check passed")

    return dataframe

# ============================================================
# FINAL CURATED TRANSFORMATION
# ============================================================

def transform_to_curated(dataframe):
    """
    Complete RAW → CURATED transformation.
    """

    logger.info("Starting RAW → CURATED transformation")

    # 1. Validate source contract
    dataframe = validate_source_schema(dataframe)

    # 2. Standardize column names
    dataframe = rename_columns(dataframe)

    # 3. Select only curated columns
    #
    # This intentionally removes source-only fields such as:
    # No, persen, percentage, or future unexpected fields.
    dataframe = dataframe[EXPECTED_CURATED_COLUMNS].copy()

    # 4. Cast data types
    dataframe = cast_datatypes(dataframe)

    # 5. Quality checks
    dataframe = quality_check(dataframe)

    logger.info(
        f"RAW → CURATED completed. "
        f"Rows: {len(dataframe):,}, "
        f"Columns: {len(dataframe.columns)}"
    )

    return dataframe

dfs = load_raw(
    datetime.strptime("2026-08-30", "%Y-%m-%d").date(),
    datetime.strptime("2026-09-01", "%Y-%m-%d").date()
)

df_raw = dfs[
    "raw/idx/year=2026/month=08/data.parquet"
]

df_curated = transform_to_curated(df_raw)

In [95]:
dfs = load_raw(
    datetime.strptime("2026-08-30", "%Y-%m-%d").date(),
    datetime.strptime("2026-09-01", "%Y-%m-%d").date()
)

df_raw = dfs[
    "raw/idx/year=2026/month=08/data.parquet"
]

df_curated = transform_to_curated(df_raw)

WARNING:__main__:Unexpected source columns detected: ['No', 'percentage', 'persen']
WARNING:__main__:Negative sentinel values detected in 'first_trade_price': 2 rows. Converting to NULL.
WARNING:__main__:OHLC anomaly - Open < Low: 3768 rows
WARNING:__main__:OHLC anomaly - Close > High: 2472 rows

In [23]:
import logging
from io import BytesIO
from datetime import datetime, timedelta, date

import boto3
import pandas as pd
from botocore.exceptions import ClientError

BUCKET_NAME = "afdal-idx-stock-data-s3"

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

# Mapping column
STANDARDIZE_COLUMN_MAP = {
    "IDStockSummary": "stock_summary_id",
    "Date": "trade_date",
    "StockCode": "stock_code",
    "StockName": "stock_name",
    "Remarks": "remarks",
    "DelistingDate": "delisting_date",

    "Previous": "previous_price",
    "OpenPrice": "open_price",
    "FirstTrade": "first_trade_price",
    "High": "high_price",
    "Low": "low_price",
    "Close": "close_price",
    "Change": "price_change",

    "Volume": "volume",
    "Value": "trading_value",
    "Frequency": "frequency",

    "IndexIndividual": "individual_index",

    "Offer": "offer_price",
    "OfferVolume": "offer_volume",
    "Bid": "bid_price",
    "BidVolume": "bid_volume",

    "ListedShares": "listed_shares",
    "TradebleShares": "tradeable_shares",
    "WeightForIndex": "index_weight",

    "ForeignSell": "foreign_sell",
    "ForeignBuy": "foreign_buy",

    "NonRegularVolume": "non_regular_volume",
    "NonRegularValue": "non_regular_value",
    "NonRegularFrequency": "non_regular_frequency",
}

EXPECTED_SOURCE_COLUMNS = set(STANDARDIZE_COLUMN_MAP.keys())
EXPECTED_CURATED_COLUMNS = list(STANDARDIZE_COLUMN_MAP.values())

# Data type
INTEGER_COLUMNS = [
    "stock_summary_id", "volume", "frequency", "offer_volume", "bid_volume",
    "listed_shares", "tradeable_shares", "foreign_sell", "foreign_buy",
    "non_regular_volume", "non_regular_frequency",
]

FLOAT_COLUMNS = [
    "previous_price", "open_price", "first_trade_price", "high_price", "low_price",
    "close_price", "price_change", "trading_value", "individual_index",
    "offer_price", "bid_price", "index_weight", "non_regular_value",
]

STRING_COLUMNS = ["stock_code", "stock_name", "remarks"]
DATE_COLUMNS = ["trade_date", "delisting_date"]


# S3
# def read_df_from_s3(bucket_name, key, s3_client=None):
#     s3_client = s3_client or boto3.client("s3")
#     response = s3_client.get_object(Bucket=bucket_name, Key=key)
#     buffer = BytesIO(response["Body"].read())
#     return pd.read_parquet(buffer)

def read_df_from_s3(bucket_name, key, s3_client=None):
    s3_client = s3_client or boto3.client("s3")
    try:
        response = s3_client.get_object(
            Bucket=bucket_name,
            Key=key,
        )
    except ClientError as e:
        if e.response["Error"]["Code"] in ("NoSuchKey", "404"):
            return None
        raise

    return pd.read_parquet(BytesIO(response["Body"].read()))



def upload_df_to_s3(df, bucket_name, key, s3_client=None):
    s3_client = s3_client or boto3.client("s3")
    buffer = BytesIO()
    df.to_parquet(buffer, index=False, engine="pyarrow")
    s3_client.put_object(Bucket=bucket_name, Key=key, Body=buffer.getvalue())


def save_curated_to_s3(dfs:dict):
    s3_client = boto3.client("s3")
    for key,value in dfs.items():
        curated_key = key.replace("raw/", "curated/", 1)
        logger.info(f"Uploading curated: {curated_key} ({len(value)} rows)")
        upload_df_to_s3(value, BUCKET_NAME, curated_key, s3_client)


def get_month_list(start_date, end_date):
    months = set()
    current_date = start_date
    while current_date <= end_date:
        months.add(current_date.year * 100 + current_date.month)
        current_date += timedelta(days=1)
    return sorted(months)


def load_raw(start_date, end_date):
    """Load raw data for a date range and return it as one concatenated DataFrame."""
    months = get_month_list(start_date, end_date)
    s3_client = boto3.client("s3")
    dfs = {}

    for i, year_month in enumerate(months):
        month, year = year_month % 100, year_month // 100
        mm, yyyy = f"{month:02d}", f"{year:04d}"

        if i != len(months) - 1:
            key = f"raw/idx/year={yyyy}/month={mm}/data.parquet"
            logger.info(f"Loading raw: {key}")
            dfs[key] = read_df_from_s3(BUCKET_NAME, key, s3_client)
        else:
            first_date = date(year, month, 1) if len(months) > 1 else start_date
            for current_date in pd.date_range(first_date, end_date):
                current_date = current_date.date()
                key = f"raw/idx/year={yyyy}/month={mm}/daily/date={current_date}/data.parquet"
                logger.info(f"Loading raw: {key}")

                df = read_df_from_s3(BUCKET_NAME, key, s3_client)
                if df is not None:
                    dfs[key] = df
                else:
                    logger.info(f"No data found: {key}")

    logger.info(f"Loaded {len(dfs)} raw files")
    return dfs


# Validation
def validate_source_schema(dataframe):
    actual_columns = set(dataframe.columns)
    missing_columns = EXPECTED_SOURCE_COLUMNS - actual_columns
    unexpected_columns = actual_columns - EXPECTED_SOURCE_COLUMNS

    if missing_columns:
        raise ValueError(f"Source schema validation failed. Missing columns: {sorted(missing_columns)}")

    if unexpected_columns:
        logger.warning(f"Unexpected source columns detected: {sorted(unexpected_columns)}")

    logger.info("Source schema validation passed")
    return dataframe


def rename_columns(dataframe):
    return dataframe.rename(columns=STANDARDIZE_COLUMN_MAP)


# Data type casting
def cast_numeric_column(dataframe, column, dtype):
    original = dataframe[column]
    original_null = original.isna()
    converted = pd.to_numeric(original, errors="coerce")

    conversion_error_mask = ~original_null & converted.isna()
    conversion_error_count = conversion_error_mask.sum()

    if conversion_error_count > 0:
        bad_values = original[conversion_error_mask].unique()
        raise ValueError(
            f"Datatype conversion failed for column '{column}'. "
            f"{conversion_error_count} invalid values. Examples: {bad_values[:5]}"
        )

    dataframe[column] = converted.astype(dtype)
    return dataframe


def cast_datatypes(dataframe):
    """Apply the curated data type contract."""
    for column in INTEGER_COLUMNS:
        dataframe = cast_numeric_column(dataframe, column, "Int64")

    for column in FLOAT_COLUMNS:
        dataframe = cast_numeric_column(dataframe, column, "float64")

    for column in STRING_COLUMNS:
        dataframe[column] = dataframe[column].astype("string").str.strip()

    for column in DATE_COLUMNS:
        dataframe[column] = pd.to_datetime(dataframe[column], errors="coerce").dt.date

    logger.info("Datatype casting passed")
    return dataframe


def quality_check(dataframe):
    errors = []

    # 1. Required columns must not be null
    for column in ["trade_date", "stock_code"]:
        if dataframe[column].isna().any():
            errors.append(f"NULL found in required column '{column}': {dataframe[column].isna().sum()} rows")

    # 2. Required string values must not be empty
    empty_stock_code = dataframe["stock_code"].fillna("").str.strip().eq("")
    if empty_stock_code.any():
        errors.append(f"Empty stock_code: {empty_stock_code.sum()} rows")

    # 3. Duplicate grain
    grain_columns = ["trade_date", "stock_code"]
    duplicate_mask = dataframe.duplicated(subset=grain_columns, keep=False)
    if duplicate_mask.any():
        errors.append(f"Duplicate grain detected for ({', '.join(grain_columns)}): {duplicate_mask.sum()} rows")

    # 4. Non-negative values - IDX uses sentinels like -9999999, treat as NULL
    non_negative_columns = [
        "previous_price", "open_price", "first_trade_price", "high_price", "low_price", "close_price",
        "volume", "trading_value", "frequency",
        "offer_price", "offer_volume", "bid_price", "bid_volume",
        "listed_shares", "tradeable_shares",
        "foreign_sell", "foreign_buy",
        "non_regular_volume", "non_regular_value", "non_regular_frequency",
    ]
    for column in non_negative_columns:
        invalid_mask = dataframe[column] < 0
        if invalid_mask.any():
            logger.warning(f"Negative sentinel values in '{column}': {invalid_mask.sum()} rows. Converting to NULL.")
            dataframe.loc[invalid_mask, column] = pd.NA

    # 5. OHLC consistency (log only, not hard failures)
    ohlc_validations = {
        "High < Low": dataframe["high_price"] < dataframe["low_price"],
        "Open < Low": dataframe["open_price"] < dataframe["low_price"],
        "Open > High": dataframe["open_price"] > dataframe["high_price"],
        "Close < Low": dataframe["close_price"] < dataframe["low_price"],
        "Close > High": dataframe["close_price"] > dataframe["high_price"],
    }
    for rule, invalid_mask in ohlc_validations.items():
        if invalid_mask.sum() > 0:
            logger.warning(f"OHLC anomaly - {rule}: {invalid_mask.sum()} rows")

    # 6. Future trade date
    today = date.today()
    future_date_mask = dataframe["trade_date"] > today
    if future_date_mask.any():
        errors.append(f"trade_date in the future: {future_date_mask.sum()} rows")

    if errors:
        raise ValueError("Quality check failed:\n- " + "\n- ".join(errors))

    logger.info("Quality check passed")
    return dataframe


def transform_to_curated(dfs:dict):
    """Complete RAW -> CURATED transformation."""
    dfs_curated = {}
    logger.info("Starting RAW -> CURATED transformation")
    for key,value in dfs.items():
        dataframe = validate_source_schema(value)
        dataframe = rename_columns(dataframe)
        dataframe = dataframe[EXPECTED_CURATED_COLUMNS].copy()  # drops source-only fields (No, persen, etc.)
        dataframe = cast_datatypes(dataframe)
        dataframe = quality_check(dataframe)

        logger.info(f"Key : {key} \n RAW -> CURATED completed. Rows: {len(dataframe):,}, Columns: {len(dataframe.columns)}")
        dfs_curated[key] = dataframe
    return dfs_curated


# if __name__ == "__main__":
#     df_raw = load_raw(
#         datetime.strptime("2026-08-30", "%Y-%m-%d").date(),
#         datetime.strptime("2026-09-01", "%Y-%m-%d").date(),
#     )
#     df_curated = transform_to_curated(df_raw)
#     save_curated_to_s3(df_curated)

In [25]:
df_raw = load_raw(
    datetime.strptime("2021-01-01", "%Y-%m-%d").date(),
    datetime.strptime("2026-01-01", "%Y-%m-%d").date(),
)
# df_raw
df_curated = transform_to_curated(df_raw)
save_curated_to_s3(df_curated)

2026-09-15 11:46:14,563 - INFO - Loading raw: raw/idx/year=2021/month=01/data.parquet
2026-09-15 11:46:16,877 - INFO - Loading raw: raw/idx/year=2021/month=02/data.parquet
2026-09-15 11:46:18,685 - INFO - Loading raw: raw/idx/year=2021/month=03/data.parquet
2026-09-15 11:46:20,058 - INFO - Loading raw: raw/idx/year=2021/month=04/data.parquet
2026-09-15 11:46:21,444 - INFO - Loading raw: raw/idx/year=2021/month=05/data.parquet
2026-09-15 11:46:22,568 - INFO - Loading raw: raw/idx/year=2021/month=06/data.parquet
2026-09-15 11:46:24,105 - INFO - Loading raw: raw/idx/year=2021/month=07/data.parquet
2026-09-15 11:46:25,776 - INFO - Loading raw: raw/idx/year=2021/month=08/data.parquet
2026-09-15 11:46:27,746 - INFO - Loading raw: raw/idx/year=2021/month=09/data.parquet
2026-09-15 11:46:30,374 - INFO - Loading raw: raw/idx/year=2021/month=10/data.parquet
2026-09-15 11:46:33,934 - INFO - Loading raw: raw/idx/year=2021/month=11/data.parquet
2026-09-15 11:46:37,106 - INFO - Loading raw: raw/idx/year=2021/month=12/data.parquet
2026-09-15 11:46:40,067 - INFO - Loading raw: raw/idx/year=2022/month=01/data.parquet
2026-09-15 11:46:42,007 - INFO - Loading raw: raw/idx/year=2022/month=02/data.parquet
2026-09-15 11:46:43,837 - INFO - Loading raw: raw/idx/year=2022/month=03/data.parquet
2026-09-15 11:46:45,557 - INFO - Loading raw: raw/idx/year=2022/month=04/data.parquet
2026-09-15 11:46:48,215 - INFO - Loading raw: raw/idx/year=2022/month=05/data.parquet
2026-09-15 11:46:50,418 - INFO - Loading raw: raw/idx/year=2022/month=06/data.parquet
2026-09-15 11:46:53,210 - INFO - Loading raw: raw/idx/year=2022/month=07/data.parquet
2026-09-15 11:46:55,785 - INFO - Loading raw: raw/idx/year=2022/month=08/data.parquet
2026-09-15 11:46:57,926 - INFO - Loading raw: raw/idx/year=2022/month=09/data.parquet
2026-09-15 11:46:59,464 - INFO - Loading raw: raw/idx/year=2022/month=10/data.parquet
2026-09-15 11:47:01,016 - INFO - Loading raw: raw/idx/year=2022/month=11/data.parquet
2026-09-15 11:47:02,766 - INFO - Loading raw: raw/idx/year=2022/month=12/data.parquet
2026-09-15 11:47:05,202 - INFO - Loading raw: raw/idx/year=2023/month=01/data.parquet
2026-09-15 11:47:07,182 - INFO - Loading raw: raw/idx/year=2023/month=02/data.parquet
2026-09-15 11:47:09,729 - INFO - Loading raw: raw/idx/year=2023/month=03/data.parquet
2026-09-15 11:47:11,712 - INFO - Loading raw: raw/idx/year=2023/month=04/data.parquet
2026-09-15 11:47:13,277 - INFO - Loading raw: raw/idx/year=2023/month=05/data.parquet
2026-09-15 11:47:15,480 - INFO - Loading raw: raw/idx/year=2023/month=06/data.parquet
2026-09-15 11:47:17,704 - INFO - Loading raw: raw/idx/year=2023/month=07/data.parquet
2026-09-15 11:47:22,678 - INFO - Loading raw: raw/idx/year=2023/month=08/data.parquet
2026-09-15 11:47:25,843 - INFO - Loading raw: raw/idx/year=2023/month=09/data.parquet
2026-09-15 11:47:28,424 - INFO - Loading raw: raw/idx/year=2023/month=10/data.parquet
2026-09-15 11:47:30,339 - INFO - Loading raw: raw/idx/year=2023/month=11/data.parquet
2026-09-15 11:47:31,757 - INFO - Loading raw: raw/idx/year=2023/month=12/data.parquet
2026-09-15 11:47:32,936 - INFO - Loading raw: raw/idx/year=2024/month=01/data.parquet
2026-09-15 11:47:34,539 - INFO - Loading raw: raw/idx/year=2024/month=02/data.parquet
2026-09-15 11:47:35,889 - INFO - Loading raw: raw/idx/year=2024/month=03/data.parquet
2026-09-15 11:47:37,520 - INFO - Loading raw: raw/idx/year=2024/month=04/data.parquet
2026-09-15 11:47:39,605 - INFO - Loading raw: raw/idx/year=2024/month=05/data.parquet
2026-09-15 11:47:41,571 - INFO - Loading raw: raw/idx/year=2024/month=06/data.parquet
2026-09-15 11:47:43,506 - INFO - Loading raw: raw/idx/year=2024/month=07/data.parquet
2026-09-15 11:47:48,024 - INFO - Loading raw: raw/idx/year=2024/month=08/data.parquet
2026-09-15 11:47:51,482 - INFO - Loading raw: raw/idx/year=2024/month=09/data.parquet
2026-09-15 11:47:54,021 - INFO - Loading raw: raw/idx/year=2024/month=10/data.parquet
2026-09-15 11:47:56,724 - INFO - Loading raw: raw/idx/year=2024/month=11/data.parquet
2026-09-15 11:47:58,671 - INFO - Loading raw: raw/idx/year=2024/month=12/data.parquet
2026-09-15 11:48:00,421 - INFO - Loading raw: raw/idx/year=2025/month=01/data.parquet
2026-09-15 11:48:02,137 - INFO - Loading raw: raw/idx/year=2025/month=02/data.parquet
2026-09-15 11:48:03,835 - INFO - Loading raw: raw/idx/year=2025/month=03/data.parquet
2026-09-15 11:48:05,626 - INFO - Loading raw: raw/idx/year=2025/month=04/data.parquet
2026-09-15 11:48:05,845 - INFO - Loading raw: raw/idx/year=2025/month=05/data.parquet
2026-09-15 11:48:08,425 - INFO - Loading raw: raw/idx/year=2025/month=06/data.parquet
2026-09-15 11:48:11,021 - INFO - Loading raw: raw/idx/year=2025/month=07/data.parquet
2026-09-15 11:48:13,974 - INFO - Loading raw: raw/idx/year=2025/month=08/data.parquet
2026-09-15 11:48:16,113 - INFO - Loading raw: raw/idx/year=2025/month=09/data.parquet
2026-09-15 11:48:17,651 - INFO - Loading raw: raw/idx/year=2025/month=10/data.parquet
2026-09-15 11:48:19,397 - INFO - Loading raw: raw/idx/year=2025/month=11/data.parquet
2026-09-15 11:48:21,543 - INFO - Loading raw: raw/idx/year=2025/month=12/data.parquet
2026-09-15 11:48:23,960 - INFO - Loading raw: raw/idx/year=2026/month=01/daily/date=2026-01-01/data.parquet
2026-09-15 11:48:24,180 - INFO - No data found: raw/idx/year=2026/month=01/daily/date=2026-01-01/data.parquet
2026-09-15 11:48:24,180 - INFO - Loaded 60 raw files
2026-09-15 11:48:24,180 - INFO - Starting RAW -> CURATED transformation
2026-09-15 11:48:24,180 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:24,180 - INFO - Source schema validation passed
2026-09-15 11:48:24,230 - INFO - Datatype casting passed
2026-09-15 11:48:24,239 - WARNING - OHLC anomaly - Open < Low: 11881 rows
2026-09-15 11:48:24,239 - WARNING - OHLC anomaly - Close > High: 1589 rows
2026-09-15 11:48:24,239 - INFO - Quality check passed
2026-09-15 11:48:24,239 - INFO - Key : raw/idx/year=2021/month=01/data.parquet
 RAW -> CURATED completed. Rows: 14,369, Columns: 29
2026-09-15 11:48:24,239 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:24,247 - INFO - Source schema validation passed
2026-09-15 11:48:24,284 - INFO - Datatype casting passed
2026-09-15 11:48:24,293 - WARNING - OHLC anomaly - Open < Low: 11370 rows
2026-09-15 11:48:24,298 - WARNING - OHLC anomaly - Close > High: 1507 rows
2026-09-15 11:48:24,300 - INFO - Quality check passed
2026-09-15 11:48:24,301 - INFO - Key : raw/idx/year=2021/month=02/data.parquet
 RAW -> CURATED completed. Rows: 13,731, Columns: 29
2026-09-15 11:48:24,302 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:24,303 - INFO - Source schema validation passed
2026-09-15 11:48:24,345 - INFO - Datatype casting passed
2026-09-15 11:48:24,357 - WARNING - OHLC anomaly - Open < Low: 13106 rows
2026-09-15 11:48:24,359 - WARNING - OHLC anomaly - Close > High: 1847 rows
2026-09-15 11:48:24,359 - INFO - Quality check passed
2026-09-15 11:48:24,359 - INFO - Key : raw/idx/year=2021/month=03/data.parquet
 RAW -> CURATED completed. Rows: 15,943, Columns: 29
2026-09-15 11:48:24,362 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:24,363 - INFO - Source schema validation passed
2026-09-15 11:48:24,406 - INFO - Datatype casting passed
2026-09-15 11:48:24,415 - WARNING - OHLC anomaly - Open < Low: 12697 rows
2026-09-15 11:48:24,415 - WARNING - OHLC anomaly - Close > High: 1690 rows
2026-09-15 11:48:24,415 - INFO - Quality check passed
2026-09-15 11:48:24,415 - INFO - Key : raw/idx/year=2021/month=04/data.parquet
 RAW -> CURATED completed. Rows: 15,329, Columns: 29
2026-09-15 11:48:24,415 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:24,421 - INFO - Source schema validation passed
2026-09-15 11:48:24,448 - INFO - Datatype casting passed
2026-09-15 11:48:24,465 - WARNING - OHLC anomaly - Open < Low: 10393 rows
2026-09-15 11:48:24,466 - WARNING - OHLC anomaly - Close > High: 1990 rows
2026-09-15 11:48:24,467 - INFO - Quality check passed
2026-09-15 11:48:24,468 - INFO - Key : raw/idx/year=2021/month=05/data.parquet
 RAW -> CURATED completed. Rows: 13,164, Columns: 29
2026-09-15 11:48:24,469 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:24,469 - INFO - Source schema validation passed
2026-09-15 11:48:24,510 - INFO - Datatype casting passed
2026-09-15 11:48:24,519 - WARNING - OHLC anomaly - Open < Low: 12811 rows
2026-09-15 11:48:24,519 - WARNING - OHLC anomaly - Close > High: 1669 rows
2026-09-15 11:48:24,521 - INFO - Quality check passed
2026-09-15 11:48:24,521 - INFO - Key : raw/idx/year=2021/month=06/data.parquet
 RAW -> CURATED completed. Rows: 15,424, Columns: 29
2026-09-15 11:48:24,521 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:24,521 - INFO - Source schema validation passed
2026-09-15 11:48:24,568 - INFO - Datatype casting passed
2026-09-15 11:48:24,575 - WARNING - OHLC anomaly - Open < Low: 12896 rows
2026-09-15 11:48:24,576 - WARNING - OHLC anomaly - Close > High: 1712 rows
2026-09-15 11:48:24,577 - INFO - Quality check passed
2026-09-15 11:48:24,578 - INFO - Key : raw/idx/year=2021/month=07/data.parquet
 RAW -> CURATED completed. Rows: 15,551, Columns: 29
2026-09-15 11:48:24,578 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:24,579 - INFO - Source schema validation passed
2026-09-15 11:48:24,650 - INFO - Datatype casting passed
2026-09-15 11:48:24,658 - WARNING - OHLC anomaly - Open < Low: 12367 rows
2026-09-15 11:48:24,658 - WARNING - OHLC anomaly - Close > High: 1590 rows
2026-09-15 11:48:24,661 - INFO - Quality check passed
2026-09-15 11:48:24,661 - INFO - Key : raw/idx/year=2021/month=08/data.parquet
 RAW -> CURATED completed. Rows: 14,856, Columns: 29
2026-09-15 11:48:24,661 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:24,663 - INFO - Source schema validation passed
2026-09-15 11:48:24,705 - INFO - Datatype casting passed
2026-09-15 11:48:24,715 - WARNING - OHLC anomaly - Open < Low: 13774 rows
2026-09-15 11:48:24,715 - WARNING - OHLC anomaly - Close > High: 1761 rows
2026-09-15 11:48:24,715 - INFO - Quality check passed
2026-09-15 11:48:24,715 - INFO - Key : raw/idx/year=2021/month=09/data.parquet
 RAW -> CURATED completed. Rows: 16,525, Columns: 29
2026-09-15 11:48:24,715 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:24,715 - INFO - Source schema validation passed
2026-09-15 11:48:24,761 - INFO - Datatype casting passed
2026-09-15 11:48:24,770 - WARNING - OHLC anomaly - Open < Low: 12644 rows
2026-09-15 11:48:24,771 - WARNING - OHLC anomaly - Close > High: 1521 rows
2026-09-15 11:48:24,772 - INFO - Quality check passed
2026-09-15 11:48:24,773 - INFO - Key : raw/idx/year=2021/month=10/data.parquet
 RAW -> CURATED completed. Rows: 15,065, Columns: 29
2026-09-15 11:48:24,773 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:24,774 - INFO - Source schema validation passed
2026-09-15 11:48:24,820 - INFO - Datatype casting passed
2026-09-15 11:48:24,830 - WARNING - OHLC anomaly - Open < Low: 14099 rows
2026-09-15 11:48:24,831 - WARNING - OHLC anomaly - Close > High: 1538 rows
2026-09-15 11:48:24,832 - INFO - Quality check passed
2026-09-15 11:48:24,834 - INFO - Key : raw/idx/year=2021/month=11/data.parquet
 RAW -> CURATED completed. Rows: 16,625, Columns: 29
2026-09-15 11:48:24,836 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:24,837 - INFO - Source schema validation passed
2026-09-15 11:48:24,885 - INFO - Datatype casting passed
2026-09-15 11:48:24,901 - WARNING - OHLC anomaly - Open < Low: 14183 rows
2026-09-15 11:48:24,903 - WARNING - OHLC anomaly - Close > High: 1683 rows
2026-09-15 11:48:24,906 - INFO - Quality check passed
2026-09-15 11:48:24,906 - INFO - Key : raw/idx/year=2021/month=12/data.parquet
 RAW -> CURATED completed. Rows: 16,854, Columns: 29
2026-09-15 11:48:24,906 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:24,906 - INFO - Source schema validation passed
2026-09-15 11:48:24,958 - INFO - Datatype casting passed
2026-09-15 11:48:24,969 - WARNING - OHLC anomaly - Open < Low: 13690 rows
2026-09-15 11:48:24,970 - WARNING - OHLC anomaly - Close > High: 1562 rows
2026-09-15 11:48:24,972 - INFO - Quality check passed
2026-09-15 11:48:24,973 - INFO - Key : raw/idx/year=2022/month=01/data.parquet
 RAW -> CURATED completed. Rows: 16,197, Columns: 29
2026-09-15 11:48:24,974 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:24,975 - INFO - Source schema validation passed
2026-09-15 11:48:25,016 - INFO - Datatype casting passed
2026-09-15 11:48:25,026 - WARNING - OHLC anomaly - Open < Low: 11756 rows
2026-09-15 11:48:25,027 - WARNING - OHLC anomaly - Close > High: 1396 rows
2026-09-15 11:48:25,028 - INFO - Quality check passed
2026-09-15 11:48:25,028 - INFO - Key : raw/idx/year=2022/month=02/data.parquet
 RAW -> CURATED completed. Rows: 13,962, Columns: 29
2026-09-15 11:48:25,030 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:25,030 - INFO - Source schema validation passed
2026-09-15 11:48:25,077 - INFO - Datatype casting passed
2026-09-15 11:48:25,087 - WARNING - OHLC anomaly - Open < Low: 14418 rows
2026-09-15 11:48:25,087 - WARNING - OHLC anomaly - Close > High: 1744 rows
2026-09-15 11:48:25,089 - INFO - Quality check passed
2026-09-15 11:48:25,089 - INFO - Key : raw/idx/year=2022/month=03/data.parquet
 RAW -> CURATED completed. Rows: 17,152, Columns: 29
2026-09-15 11:48:25,089 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:25,091 - INFO - Source schema validation passed
2026-09-15 11:48:25,139 - INFO - Datatype casting passed
2026-09-15 11:48:25,147 - WARNING - OHLC anomaly - Open < Low: 12619 rows
2026-09-15 11:48:25,148 - WARNING - OHLC anomaly - Close > High: 1437 rows
2026-09-15 11:48:25,149 - INFO - Quality check passed
2026-09-15 11:48:25,150 - INFO - Key : raw/idx/year=2022/month=04/data.parquet
 RAW -> CURATED completed. Rows: 14,911, Columns: 29
2026-09-15 11:48:25,151 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:25,152 - INFO - Source schema validation passed
2026-09-15 11:48:25,194 - INFO - Datatype casting passed
2026-09-15 11:48:25,203 - WARNING - OHLC anomaly - Open < Low: 10010 rows
2026-09-15 11:48:25,203 - WARNING - OHLC anomaly - Close > High: 1149 rows
2026-09-15 11:48:25,206 - INFO - Quality check passed
2026-09-15 11:48:25,206 - INFO - Key : raw/idx/year=2022/month=05/data.parquet
 RAW -> CURATED completed. Rows: 11,833, Columns: 29
2026-09-15 11:48:25,206 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:25,206 - INFO - Source schema validation passed
2026-09-15 11:48:25,259 - INFO - Datatype casting passed
2026-09-15 11:48:25,270 - WARNING - OHLC anomaly - Open < Low: 13929 rows
2026-09-15 11:48:25,271 - WARNING - OHLC anomaly - Close > High: 1718 rows
2026-09-15 11:48:25,271 - INFO - Quality check passed
2026-09-15 11:48:25,272 - INFO - Key : raw/idx/year=2022/month=06/data.parquet
 RAW -> CURATED completed. Rows: 16,590, Columns: 29
2026-09-15 11:48:25,273 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:25,275 - INFO - Source schema validation passed
2026-09-15 11:48:25,317 - INFO - Datatype casting passed
2026-09-15 11:48:25,327 - WARNING - OHLC anomaly - Open < Low: 13864 rows
2026-09-15 11:48:25,328 - WARNING - OHLC anomaly - Close > High: 1875 rows
2026-09-15 11:48:25,329 - INFO - Quality check passed
2026-09-15 11:48:25,330 - INFO - Key : raw/idx/year=2022/month=07/data.parquet
 RAW -> CURATED completed. Rows: 16,682, Columns: 29
2026-09-15 11:48:25,330 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:25,332 - INFO - Source schema validation passed
2026-09-15 11:48:25,378 - INFO - Datatype casting passed
2026-09-15 11:48:25,388 - WARNING - OHLC anomaly - Open < Low: 14731 rows
2026-09-15 11:48:25,389 - WARNING - OHLC anomaly - Close > High: 2079 rows
2026-09-15 11:48:25,391 - INFO - Quality check passed
2026-09-15 11:48:25,391 - INFO - Key : raw/idx/year=2022/month=08/data.parquet
 RAW -> CURATED completed. Rows: 17,799, Columns: 29
2026-09-15 11:48:25,392 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:25,393 - INFO - Source schema validation passed
2026-09-15 11:48:25,443 - INFO - Datatype casting passed
2026-09-15 11:48:25,454 - WARNING - OHLC anomaly - Open < Low: 14882 rows
2026-09-15 11:48:25,456 - WARNING - OHLC anomaly - Close > High: 2010 rows
2026-09-15 11:48:25,458 - INFO - Quality check passed
2026-09-15 11:48:25,459 - INFO - Key : raw/idx/year=2022/month=09/data.parquet
 RAW -> CURATED completed. Rows: 17,882, Columns: 29
2026-09-15 11:48:25,460 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:25,461 - INFO - Source schema validation passed
2026-09-15 11:48:25,506 - INFO - Datatype casting passed
2026-09-15 11:48:25,516 - WARNING - OHLC anomaly - Open < Low: 14129 rows
2026-09-15 11:48:25,516 - WARNING - OHLC anomaly - Close > High: 2000 rows
2026-09-15 11:48:25,518 - INFO - Quality check passed
2026-09-15 11:48:25,518 - INFO - Key : raw/idx/year=2022/month=10/data.parquet
 RAW -> CURATED completed. Rows: 17,073, Columns: 29
2026-09-15 11:48:25,518 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:25,520 - INFO - Source schema validation passed
2026-09-15 11:48:25,571 - INFO - Datatype casting passed
2026-09-15 11:48:25,580 - WARNING - OHLC anomaly - Open < Low: 14989 rows
2026-09-15 11:48:25,580 - WARNING - OHLC anomaly - Close > High: 2075 rows
2026-09-15 11:48:25,580 - INFO - Quality check passed
2026-09-15 11:48:25,580 - INFO - Key : raw/idx/year=2022/month=11/data.parquet
 RAW -> CURATED completed. Rows: 18,050, Columns: 29
2026-09-15 11:48:25,580 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:25,580 - INFO - Source schema validation passed
2026-09-15 11:48:25,635 - INFO - Datatype casting passed
2026-09-15 11:48:25,646 - WARNING - OHLC anomaly - Open < Low: 15034 rows
2026-09-15 11:48:25,647 - WARNING - OHLC anomaly - Close > High: 2171 rows
2026-09-15 11:48:25,652 - INFO - Quality check passed
2026-09-15 11:48:25,652 - INFO - Key : raw/idx/year=2022/month=12/data.parquet
 RAW -> CURATED completed. Rows: 18,190, Columns: 29
2026-09-15 11:48:25,652 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:25,652 - INFO - Source schema validation passed
2026-09-15 11:48:25,701 - INFO - Datatype casting passed
2026-09-15 11:48:25,709 - WARNING - OHLC anomaly - Open < Low: 14548 rows
2026-09-15 11:48:25,710 - WARNING - OHLC anomaly - Close > High: 2033 rows
2026-09-15 11:48:25,712 - INFO - Quality check passed
2026-09-15 11:48:25,712 - INFO - Key : raw/idx/year=2023/month=01/data.parquet
 RAW -> CURATED completed. Rows: 17,526, Columns: 29
2026-09-15 11:48:25,713 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 11:48:25,713 - INFO - Source schema validation passed
2026-09-15 11:48:25,748 - INFO - Datatype casting passed
2026-09-15 11:48:25,769 - WARNING - OHLC anomaly - Open < Low: 14113 rows
2026-09-15 11:48:25,770 - WARNING - OHLC anomaly - Close > High: 1875 rows
2026-09-15 11:48:25,772 - INFO - Quality check passed

AttributeError: 'NoneType' object has no attribute 'columns'

In [32]:
df_raw = load_raw(
    datetime.strptime("2025-01-01", "%Y-%m-%d").date(),
    datetime.strptime("2026-01-01", "%Y-%m-%d").date(),
)
# df_raw
df_curated = transform_to_curated(df_raw)
save_curated_to_s3(df_curated)

2026-09-15 14:20:07,503 - INFO - Loading raw: raw/idx/year=2025/month=01/data.parquet
2026-09-15 14:20:09,538 - INFO - Loading raw: raw/idx/year=2025/month=02/data.parquet
2026-09-15 14:20:10,618 - INFO - Loading raw: raw/idx/year=2025/month=03/data.parquet
2026-09-15 14:20:11,606 - INFO - Loading raw: raw/idx/year=2025/month=04/data.parquet
2026-09-15 14:20:12,950 - INFO - Loading raw: raw/idx/year=2025/month=05/data.parquet
2026-09-15 14:20:14,116 - INFO - Loading raw: raw/idx/year=2025/month=06/data.parquet
2026-09-15 14:20:15,233 - INFO - Loading raw: raw/idx/year=2025/month=07/data.parquet
2026-09-15 14:20:16,584 - INFO - Loading raw: raw/idx/year=2025/month=08/data.parquet
2026-09-15 14:20:18,568 - INFO - Loading raw: raw/idx/year=2025/month=09/data.parquet
2026-09-15 14:20:20,118 - INFO - Loading raw: raw/idx/year=2025/month=10/data.parquet
2026-09-15 14:20:21,622 - INFO - Loading raw: raw/idx/year=2025/month=11/data.parquet
2026-09-15 14:20:22,985 - INFO - Loading raw: raw/idx/year=2025/month=12/data.parquet
2026-09-15 14:20:24,527 - INFO - Loading raw: raw/idx/year=2026/month=01/daily/date=2026-01-01/data.parquet
2026-09-15 14:20:24,737 - INFO - No data found: raw/idx/year=2026/month=01/daily/date=2026-01-01/data.parquet
2026-09-15 14:20:24,748 - INFO - Loaded 12 raw files
2026-09-15 14:20:24,751 - INFO - Starting RAW -> CURATED transformation
2026-09-15 14:20:24,751 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 14:20:24,751 - INFO - Source schema validation passed
2026-09-15 14:20:24,870 - INFO - Datatype casting passed
2026-09-15 14:20:24,882 - WARNING - Negative sentinel values in 'first_trade_price': 11 rows. Converting to NULL.
2026-09-15 14:20:24,893 - WARNING - OHLC anomaly - Open < Low: 6944 rows
2026-09-15 14:20:24,893 - WARNING - OHLC anomaly - Close > High: 2023 rows
2026-09-15 14:20:24,893 - INFO - Quality check passed
2026-09-15 14:20:24,899 - INFO - Key : raw/idx/year=2025/month=01/data.parquet
 RAW -> CURATED completed. Rows: 18,102, Columns: 29
2026-09-15 14:20:24,901 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 14:20:24,902 - INFO - Source schema validation passed
2026-09-15 14:20:24,956 - INFO - Datatype casting passed
2026-09-15 14:20:24,965 - WARNING - Negative sentinel values in 'first_trade_price': 12 rows. Converting to NULL.
2026-09-15 14:20:24,971 - WARNING - OHLC anomaly - Open < Low: 7267 rows
2026-09-15 14:20:24,971 - WARNING - OHLC anomaly - Close > High: 2379 rows
2026-09-15 14:20:24,971 - INFO - Quality check passed
2026-09-15 14:20:24,971 - INFO - Key : raw/idx/year=2025/month=02/data.parquet
 RAW -> CURATED completed. Rows: 19,100, Columns: 29
2026-09-15 14:20:24,971 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 14:20:24,971 - INFO - Source schema validation passed
2026-09-15 14:20:25,026 - INFO - Datatype casting passed
2026-09-15 14:20:25,039 - WARNING - Negative sentinel values in 'first_trade_price': 14 rows. Converting to NULL.
2026-09-15 14:20:25,039 - WARNING - OHLC anomaly - Open < Low: 7305 rows
2026-09-15 14:20:25,039 - WARNING - OHLC anomaly - Close > High: 2149 rows
2026-09-15 14:20:25,039 - INFO - Quality check passed
2026-09-15 14:20:25,048 - INFO - Key : raw/idx/year=2025/month=03/data.parquet
 RAW -> CURATED completed. Rows: 18,176, Columns: 29
2026-09-15 14:20:25,051 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 14:20:25,052 - INFO - Source schema validation passed
2026-09-15 14:20:25,115 - INFO - Datatype casting passed
2026-09-15 14:20:25,125 - WARNING - Negative sentinel values in 'first_trade_price': 11 rows. Converting to NULL.
2026-09-15 14:20:25,127 - WARNING - OHLC anomaly - Open < Low: 5290 rows
2026-09-15 14:20:25,127 - WARNING - OHLC anomaly - Close > High: 1812 rows
2026-09-15 14:20:25,130 - INFO - Quality check passed
2026-09-15 14:20:25,132 - INFO - Key : raw/idx/year=2025/month=04/data.parquet
 RAW -> CURATED completed. Rows: 15,342, Columns: 29
2026-09-15 14:20:25,133 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 14:20:25,134 - INFO - Source schema validation passed
2026-09-15 14:20:25,181 - INFO - Datatype casting passed
2026-09-15 14:20:25,183 - WARNING - Negative sentinel values in 'first_trade_price': 3 rows. Converting to NULL.
2026-09-15 14:20:25,191 - WARNING - OHLC anomaly - Open < Low: 5230 rows
2026-09-15 14:20:25,191 - WARNING - OHLC anomaly - Close > High: 1892 rows
2026-09-15 14:20:25,194 - INFO - Quality check passed
2026-09-15 14:20:25,194 - INFO - Key : raw/idx/year=2025/month=05/data.parquet
 RAW -> CURATED completed. Rows: 16,316, Columns: 29
2026-09-15 14:20:25,194 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 14:20:25,194 - INFO - Source schema validation passed
2026-09-15 14:20:25,244 - INFO - Datatype casting passed
2026-09-15 14:20:25,252 - WARNING - Negative sentinel values in 'first_trade_price': 6 rows. Converting to NULL.
2026-09-15 14:20:25,258 - WARNING - OHLC anomaly - Open < Low: 5601 rows
2026-09-15 14:20:25,258 - WARNING - OHLC anomaly - Close > High: 2097 rows
2026-09-15 14:20:25,260 - INFO - Quality check passed
2026-09-15 14:20:25,260 - INFO - Key : raw/idx/year=2025/month=06/data.parquet
 RAW -> CURATED completed. Rows: 17,280, Columns: 29
2026-09-15 14:20:25,260 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 14:20:25,260 - INFO - Source schema validation passed
2026-09-15 14:20:25,316 - INFO - Datatype casting passed
2026-09-15 14:20:25,327 - WARNING - Negative sentinel values in 'first_trade_price': 6 rows. Converting to NULL.
2026-09-15 14:20:25,337 - WARNING - OHLC anomaly - Open < Low: 6962 rows
2026-09-15 14:20:25,337 - WARNING - OHLC anomaly - Close > High: 2764 rows
2026-09-15 14:20:25,337 - INFO - Quality check passed
2026-09-15 14:20:25,337 - INFO - Key : raw/idx/year=2025/month=07/data.parquet
 RAW -> CURATED completed. Rows: 22,106, Columns: 29
2026-09-15 14:20:25,337 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 14:20:25,337 - INFO - Source schema validation passed
2026-09-15 14:20:25,390 - INFO - Datatype casting passed
2026-09-15 14:20:25,399 - WARNING - Negative sentinel values in 'first_trade_price': 1 rows. Converting to NULL.
2026-09-15 14:20:25,404 - WARNING - OHLC anomaly - Open < Low: 5322 rows
2026-09-15 14:20:25,404 - WARNING - OHLC anomaly - Close > High: 2251 rows
2026-09-15 14:20:25,404 - INFO - Quality check passed
2026-09-15 14:20:25,404 - INFO - Key : raw/idx/year=2025/month=08/data.parquet
 RAW -> CURATED completed. Rows: 19,120, Columns: 29
2026-09-15 14:20:25,404 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 14:20:25,404 - INFO - Source schema validation passed
2026-09-15 14:20:25,462 - INFO - Datatype casting passed
2026-09-15 14:20:25,471 - WARNING - Negative sentinel values in 'first_trade_price': 1 rows. Converting to NULL.
2026-09-15 14:20:25,471 - WARNING - OHLC anomaly - Open < Low: 5214 rows
2026-09-15 14:20:25,471 - WARNING - OHLC anomaly - Close > High: 2414 rows
2026-09-15 14:20:25,471 - INFO - Quality check passed
2026-09-15 14:20:25,471 - INFO - Key : raw/idx/year=2025/month=09/data.parquet
 RAW -> CURATED completed. Rows: 20,082, Columns: 29
2026-09-15 14:20:25,471 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 14:20:25,471 - INFO - Source schema validation passed
2026-09-15 14:20:25,532 - INFO - Datatype casting passed
2026-09-15 14:20:25,538 - WARNING - OHLC anomaly - Open < Low: 5735 rows
2026-09-15 14:20:25,538 - WARNING - OHLC anomaly - Close > High: 2561 rows
2026-09-15 14:20:25,549 - INFO - Quality check passed
2026-09-15 14:20:25,549 - INFO - Key : raw/idx/year=2025/month=10/data.parquet
 RAW -> CURATED completed. Rows: 21,987, Columns: 29
2026-09-15 14:20:25,549 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 14:20:25,549 - INFO - Source schema validation passed
2026-09-15 14:20:25,604 - INFO - Datatype casting passed
2026-09-15 14:20:25,614 - WARNING - OHLC anomaly - Open < Low: 4646 rows
2026-09-15 14:20:25,616 - WARNING - OHLC anomaly - Close > High: 2091 rows
2026-09-15 14:20:25,616 - INFO - Quality check passed
2026-09-15 14:20:25,616 - INFO - Key : raw/idx/year=2025/month=11/data.parquet
 RAW -> CURATED completed. Rows: 19,117, Columns: 29
2026-09-15 14:20:25,616 - WARNING - Unexpected source columns detected: ['No', 'percentage', 'persen']
2026-09-15 14:20:25,616 - INFO - Source schema validation passed
2026-09-15 14:20:25,673 - INFO - Datatype casting passed
2026-09-15 14:20:25,682 - WARNING - OHLC anomaly - Open < Low: 4170 rows
2026-09-15 14:20:25,682 - WARNING - OHLC anomaly - Close > High: 2273 rows
2026-09-15 14:20:25,682 - INFO - Quality check passed
2026-09-15 14:20:25,682 - INFO - Key : raw/idx/year=2025/month=12/data.parquet
 RAW -> CURATED completed. Rows: 19,143, Columns: 29
2026-09-15 14:20:25,781 - INFO - Uploading curated: curated/idx/year=2025/month=01/data.parquet (18102 rows)
2026-09-15 14:20:28,370 - INFO - Uploading curated: curated/idx/year=2025/month=02/data.parquet (19100 rows)
2026-09-15 14:20:29,434 - INFO - Uploading curated: curated/idx/year=2025/month=03/data.parquet (18176 rows)
2026-09-15 14:20:30,174 - INFO - Uploading curated: curated/idx/year=2025/month=04/data.parquet (15342 rows)
2026-09-15 14:20:30,921 - INFO - Uploading curated: curated/idx/year=2025/month=05/data.parquet (16316 rows)
2026-09-15 14:20:31,724 - INFO - Uploading curated: curated/idx/year=2025/month=06/data.parquet (17280 rows)
2026-09-15 14:20:32,457 - INFO - Uploading curated: curated/idx/year=2025/month=07/data.parquet (22106 rows)
2026-09-15 14:20:33,566 - INFO - Uploading curated: curated/idx/year=2025/month=08/data.parquet (19120 rows)
2026-09-15 14:20:34,365 - INFO - Uploading curated: curated/idx/year=2025/month=09/data.parquet (20082 rows)
2026-09-15 14:20:35,186 - INFO - Uploading curated: curated/idx/year=2025/month=10/data.parquet (21987 rows)
2026-09-15 14:20:35,994 - INFO - Uploading curated: curated/idx/year=2025/month=11/data.parquet (19117 rows)
2026-09-15 14:20:36,721 - INFO - Uploading curated: curated/idx/year=2025/month=12/data.parquet (19143 rows)

In [92]:
s3 = boto3.client("s3")
response = s3.list_objects_v2(
    Bucket = BUCKET_NAME,
    Prefix = 'curated/idx'
)

for obj in response.get('Contents'):
    print(obj["Key"])

curated/idx/year=2020/month=01/data.parquet
curated/idx/year=2020/month=02/data.parquet
curated/idx/year=2020/month=03/data.parquet
curated/idx/year=2020/month=04/data.parquet
curated/idx/year=2020/month=05/data.parquet
curated/idx/year=2020/month=06/data.parquet
curated/idx/year=2020/month=07/data.parquet
curated/idx/year=2020/month=08/data.parquet
curated/idx/year=2020/month=09/data.parquet
curated/idx/year=2020/month=10/data.parquet
curated/idx/year=2020/month=11/data.parquet
curated/idx/year=2020/month=12/data.parquet
curated/idx/year=2021/month=01/data.parquet
curated/idx/year=2021/month=02/data.parquet
curated/idx/year=2021/month=03/data.parquet
curated/idx/year=2021/month=04/data.parquet
curated/idx/year=2021/month=05/data.parquet
curated/idx/year=2021/month=06/data.parquet
curated/idx/year=2021/month=07/data.parquet
curated/idx/year=2021/month=08/data.parquet
curated/idx/year=2021/month=09/data.parquet
curated/idx/year=2021/month=10/data.parquet
curated/idx/year=2021/month=11/data.parquet
curated/idx/year=2021/month=12/data.parquet
curated/idx/year=2022/month=01/data.parquet
curated/idx/year=2022/month=02/data.parquet
curated/idx/year=2022/month=03/data.parquet
curated/idx/year=2022/month=04/data.parquet
curated/idx/year=2022/month=05/data.parquet
curated/idx/year=2022/month=06/data.parquet
curated/idx/year=2022/month=07/data.parquet
curated/idx/year=2022/month=08/data.parquet
curated/idx/year=2022/month=09/data.parquet
curated/idx/year=2022/month=10/data.parquet
curated/idx/year=2022/month=11/data.parquet
curated/idx/year=2022/month=12/data.parquet
curated/idx/year=2023/month=01/data.parquet
curated/idx/year=2023/month=02/data.parquet
curated/idx/year=2023/month=03/data.parquet
curated/idx/year=2023/month=04/data.parquet
curated/idx/year=2023/month=05/data.parquet
curated/idx/year=2023/month=06/data.parquet
curated/idx/year=2023/month=07/data.parquet
curated/idx/year=2023/month=08/data.parquet
curated/idx/year=2023/month=09/data.parquet
curated/idx/year=2023/month=10/data.parquet
curated/idx/year=2023/month=11/data.parquet
curated/idx/year=2023/month=12/data.parquet
curated/idx/year=2024/month=01/data.parquet
curated/idx/year=2024/month=02/data.parquet
curated/idx/year=2024/month=03/data.parquet
curated/idx/year=2024/month=04/data.parquet
curated/idx/year=2024/month=05/data.parquet
curated/idx/year=2024/month=06/data.parquet
curated/idx/year=2024/month=07/data.parquet
curated/idx/year=2024/month=08/data.parquet
curated/idx/year=2024/month=09/data.parquet
curated/idx/year=2024/month=10/data.parquet
curated/idx/year=2024/month=11/data.parquet
curated/idx/year=2024/month=12/data.parquet
curated/idx/year=2025/month=01/data.parquet
curated/idx/year=2025/month=02/data.parquet
curated/idx/year=2025/month=03/data.parquet
curated/idx/year=2025/month=04/data.parquet
curated/idx/year=2025/month=05/data.parquet
curated/idx/year=2025/month=06/data.parquet
curated/idx/year=2025/month=07/data.parquet
curated/idx/year=2025/month=08/data.parquet
curated/idx/year=2025/month=09/data.parquet
curated/idx/year=2025/month=10/data.parquet
curated/idx/year=2025/month=11/data.parquet
curated/idx/year=2025/month=12/data.parquet
curated/idx/year=2026/month=01/data.parquet
curated/idx/year=2026/month=02/data.parquet
curated/idx/year=2026/month=03/data.parquet
curated/idx/year=2026/month=04/data.parquet
curated/idx/year=2026/month=05/data.parquet
curated/idx/year=2026/month=06/data.parquet
curated/idx/year=2026/month=07/data.parquet
curated/idx/year=2026/month=08/data.parquet
curated/idx/year=2026/month=09/daily/date=2026-09-01/data.parquet

In [94]:
response = s3.get_object(
    Bucket = BUCKET_NAME,
    Key = "curated/idx/year=2026/month=08/data.parquet"
)

df = pd.read_parquet(BytesIO(response["Body"].read()))
df.columns

Index(['stock_summary_id', 'trade_date', 'stock_code', 'stock_name', 'remarks',
       'delisting_date', 'previous_price', 'open_price', 'first_trade_price',
       'high_price', 'low_price', 'close_price', 'price_change', 'volume',
       'trading_value', 'frequency', 'individual_index', 'offer_price',
       'offer_volume', 'bid_price', 'bid_volume', 'listed_shares',
       'tradeable_shares', 'index_weight', 'foreign_sell', 'foreign_buy',
       'non_regular_volume', 'non_regular_value', 'non_regular_frequency'],
      dtype='object')

In [95]:
df["individual_index"]

0        164.0
1        572.7
2         66.3
3        799.1
4         67.7
         ...
18292     68.0
18293     35.3
18294    106.9
18295    258.4
18296     52.0
Name: individual_index, Length: 18297, dtype: float64

In [103]:
response = s3.list_objects_v2(
    Bucket = BUCKET_NAME
)
response.get("Contents")

[{'Key': 'archived/idx/',
  'LastModified': datetime.datetime(2026, 9, 6, 16, 7, 59, tzinfo=tzutc()),
  'ETag': '"d41d8cd98f00b204e9800998ecf8427e"',
  'ChecksumAlgorithm': ['CRC64NVME'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 0,
  'StorageClass': 'STANDARD'},
 {'Key': 'curated/idx/year=2026/month=08/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 13, 16, 17, 45, tzinfo=tzutc()),
  'ETag': '"c3f7a9808c73c8521a78622c63c9fd9e"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1221613,
  'StorageClass': 'STANDARD'},
 {'Key': 'curated/idx/year=2026/month=09/daily/date=2026-09-01/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 13, 16, 17, 48, tzinfo=tzutc()),
  'ETag': '"6d634b85b3a2844aa78be712e3cba86e"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 144648,
  'StorageClass': 'STANDARD'},
 {'Key': 'metadata/etl_control.json',
  'LastModified': datetime.datetime(2026, 9, 10, 16, 21, 26, tzinfo=tzutc()),
  'ETag': '"cd3d00e40c9701f4906dedcfc6dbf7af"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 306,
  'StorageClass': 'STANDARD'},
 {'Key': 'processed/idx/',
  'LastModified': datetime.datetime(2026, 9, 6, 15, 54, 9, tzinfo=tzutc()),
  'ETag': '"d41d8cd98f00b204e9800998ecf8427e"',
  'ChecksumAlgorithm': ['CRC64NVME'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 0,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/',
  'LastModified': datetime.datetime(2026, 9, 6, 15, 53, 8, tzinfo=tzutc()),
  'ETag': '"d41d8cd98f00b204e9800998ecf8427e"',
  'ChecksumAlgorithm': ['CRC64NVME'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 0,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2020/month=01/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 8, 50, 42, tzinfo=tzutc()),
  'ETag': '"79d594384896514370906f1c6f680358"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 832341,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2020/month=02/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 8, 52, 22, tzinfo=tzutc()),
  'ETag': '"fa5b98d795afc1e3fab8d144ec11da4e"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 770439,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2020/month=03/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 8, 54, 17, tzinfo=tzutc()),
  'ETag': '"d83d6ec5b2d59b75c9a80d89f8b60a35"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 791011,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2020/month=04/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 0, 14, tzinfo=tzutc()),
  'ETag': '"bee83bb43dcbe795ea80020ff4839ee2"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 758635,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2020/month=05/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 2, 3, tzinfo=tzutc()),
  'ETag': '"7553b0a7059adb48ceb2dc9affdba513"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 584910,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2020/month=06/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 3, 52, tzinfo=tzutc()),
  'ETag': '"31ad5f33ab61beb529d0b4113a261f78"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 780518,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2020/month=07/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 5, 35, tzinfo=tzutc()),
  'ETag': '"fcc1f708441c32c0df9c481d7c2f6aa3"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 823338,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2020/month=08/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 7, 21, tzinfo=tzutc()),
  'ETag': '"629961abfe86f038c2403624a37c591b"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 708004,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2020/month=09/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 9, 12, tzinfo=tzutc()),
  'ETag': '"d55e73b74b4d51b71dd80fdf269233f8"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 853643,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2020/month=10/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 11, 4, tzinfo=tzutc()),
  'ETag': '"a618feaa112338268a4c16bb9db4a36e"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 720587,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2020/month=11/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 12, 48, tzinfo=tzutc()),
  'ETag': '"ca4ab0eeed22e6fdfa1b423642c129fa"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 849717,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2020/month=12/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 14, 39, tzinfo=tzutc()),
  'ETag': '"c0bae08a8fe7faf52e6fbef598549534"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 837109,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2021/month=01/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 16, 24, tzinfo=tzutc()),
  'ETag': '"64d0e30bb066e153393a729903583c09"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 918396,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2021/month=02/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 18, 3, tzinfo=tzutc()),
  'ETag': '"aa2f80d349586d2aaf9549955349a1cc"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 819030,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2021/month=03/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 19, 52, tzinfo=tzutc()),
  'ETag': '"14a21f2fbc2e0d16eaf13be152d10c9a"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 944755,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2021/month=04/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 21, 35, tzinfo=tzutc()),
  'ETag': '"7eb54290fa9f3d53d145ae6ebf8a3ced"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 920796,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2021/month=05/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 23, 27, tzinfo=tzutc()),
  'ETag': '"13ad709fe2ecff81a8e92e1b80064e35"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 777296,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2021/month=06/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 25, 8, tzinfo=tzutc()),
  'ETag': '"730ad7923cb60d2ca60d1a16287a70d7"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 918406,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2021/month=07/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 26, 51, tzinfo=tzutc()),
  'ETag': '"b167f4f6affebcd6dd15146091c967bc"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 925642,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2021/month=08/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 28, 38, tzinfo=tzutc()),
  'ETag': '"d01550bb4443950e2bfeabdb785414fe"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 912064,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2021/month=09/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 30, 29, tzinfo=tzutc()),
  'ETag': '"82ddf41af3170f9112a40b79326185b4"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 999039,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2021/month=10/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 32, 19, tzinfo=tzutc()),
  'ETag': '"b6870bcc1586a3755073b575e23d9e11"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 939596,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2021/month=11/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 34, 4, tzinfo=tzutc()),
  'ETag': '"5e9b563b7e76d37a176e5eaff57228da"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1013170,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2021/month=12/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 35, 50, tzinfo=tzutc()),
  'ETag': '"e0dac3d00123a6f177d10089dd04af3f"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1023899,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2022/month=01/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 37, 38, tzinfo=tzutc()),
  'ETag': '"61cd82d558d4f998e03911d7af68b8e7"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 972186,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2022/month=02/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 39, 19, tzinfo=tzutc()),
  'ETag': '"5ac6ab0fbc484637c8a11a26bda3c675"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 886537,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2022/month=03/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 41, 8, tzinfo=tzutc()),
  'ETag': '"8f6add1c348b1128ab18322884fffc92"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1034082,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2022/month=04/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 42, 50, tzinfo=tzutc()),
  'ETag': '"0e3db61734074cf16c30c8c94032f977"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 940829,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2022/month=05/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 44, 37, tzinfo=tzutc()),
  'ETag': '"ac40cd07a8b6bb2ce022fe29d84c8ec3"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 766213,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2022/month=06/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 46, 15, tzinfo=tzutc()),
  'ETag': '"dd892039fad8dd89aeab1a9dfb812a3f"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1005370,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2022/month=07/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 48, 4, tzinfo=tzutc()),
  'ETag': '"8860aee82da9e009b15795b51bd9ffdf"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 993446,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2022/month=08/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 49, 46, tzinfo=tzutc()),
  'ETag': '"09c5586e6df56d53efc955dc4fd721ce"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1082040,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2022/month=09/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 51, 30, tzinfo=tzutc()),
  'ETag': '"655b8bd772db4c7d4da3556b293a6aef"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1081218,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2022/month=10/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 53, 21, tzinfo=tzutc()),
  'ETag': '"c79ee0c0a7ccf523b45fffbe13571709"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1027821,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2022/month=11/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 55, 4, tzinfo=tzutc()),
  'ETag': '"66d3bf44f3a3b1b70e8d9f2e9a9876e8"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1104654,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2022/month=12/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 56, 49, tzinfo=tzutc()),
  'ETag': '"73adcd3f8f2c3a7cec6d74172812e189"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1085341,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2023/month=01/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 9, 58, 31, tzinfo=tzutc()),
  'ETag': '"4f20a23c30bcb412e993901c0b96f3c0"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1029044,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2023/month=02/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 4, 33, tzinfo=tzutc()),
  'ETag': '"163e46a988db2d5c575d5af876ecfc7b"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1045143,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2023/month=03/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 8, 52, tzinfo=tzutc()),
  'ETag': '"a1af250a04dbc33712589431d1dfc87b"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1059604,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2023/month=04/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 10, 26, tzinfo=tzutc()),
  'ETag': '"f19f6672752ff04195c6b70b9b0bddef"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 758480,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2023/month=05/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 12, 11, tzinfo=tzutc()),
  'ETag': '"e4c788350f72c830049cd2535146429b"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1180605,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2023/month=06/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 13, 53, tzinfo=tzutc()),
  'ETag': '"772a623a0e570837782bf72d943c27c1"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 950064,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2023/month=07/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 15, 34, tzinfo=tzutc()),
  'ETag': '"b16e06ce51ad2a42eb463756e131573f"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1101637,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2023/month=08/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 17, 19, tzinfo=tzutc()),
  'ETag': '"d68c3f55e2091c2069b05c69975e3ce2"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1168485,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2023/month=09/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 19, 5, tzinfo=tzutc()),
  'ETag': '"74a239d3ffa5294c8bb0c9d4be40557c"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1105837,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2023/month=10/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 20, 48, tzinfo=tzutc()),
  'ETag': '"645cd5920478da251e832a0b9e44dc3f"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1198391,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2023/month=11/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 22, 33, tzinfo=tzutc()),
  'ETag': '"e0c123578eb05d02fd3ee09549cf8b64"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1167408,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2023/month=12/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 24, 12, tzinfo=tzutc()),
  'ETag': '"8ed2585fe7821226037e16a05e9aa2ae"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1054347,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2024/month=01/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 26, 57, tzinfo=tzutc()),
  'ETag': '"9689d439ff8fea00d7a90c7109646ab7"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1188241,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2024/month=02/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 28, 36, tzinfo=tzutc()),
  'ETag': '"cba29caa7ffffbe5d2cd3a42135ca046"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1001927,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2024/month=03/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 30, 19, tzinfo=tzutc()),
  'ETag': '"016391a3a7d50996c3ce7fea663d2246"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 954678,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2024/month=04/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 32, 4, tzinfo=tzutc()),
  'ETag': '"c8cb7baf6fdd5b9cf3a27cdc8279aec4"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 928771,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2024/month=05/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 33, 46, tzinfo=tzutc()),
  'ETag': '"886d1298b4c2077d7b21b658bfaed5f2"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1039489,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2024/month=06/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 35, 31, tzinfo=tzutc()),
  'ETag': '"38e29f2dd32cac07ee61133a8e9b8174"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1008232,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2024/month=07/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 40, 17, tzinfo=tzutc()),
  'ETag': '"da22c97b8cc0a4bac294258091a420ec"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1266090,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2024/month=08/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 41, 57, tzinfo=tzutc()),
  'ETag': '"76f2ba40f0182f4b225961239f942ac0"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1233397,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2024/month=09/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 43, 38, tzinfo=tzutc()),
  'ETag': '"6d0b1104418a217e9db632786e69eeea"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1153601,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2024/month=10/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 45, 25, tzinfo=tzutc()),
  'ETag': '"0b998600e96cc1a29acd6e910bea273a"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1297765,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2024/month=11/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 47, 8, tzinfo=tzutc()),
  'ETag': '"512ce5442f847ceeabb1ee9025fdfb22"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1145287,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2024/month=12/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 14, 10, 48, 53, tzinfo=tzutc()),
  'ETag': '"8d81c8e1adc4f7af8bd74917b6b3c3f7"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1150791,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2026/month=01/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 8, 8, 23, 3, tzinfo=tzutc()),
  'ETag': '"ca651bf354ed0021cf30e33b0249a496"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1265771,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2026/month=02/data.parquet',
  'LastModified': datetime.datetime(2026, 9, 8, 8, 34, 2, tzinfo=tzutc()),
  'ETag': '"4d9f73606a45bf9d89832b92e0518fab"',
  'ChecksumAlgorithm': ['CRC32'],
  'ChecksumType': 'FULL_OBJECT',
  'Size': 1133998,
  'StorageClass': 'STANDARD'},
 {'Key': 'raw/idx/year=2026/month=03/data.parquet',

In [8]:
import duckdb
import logging
import pandas as pd
import boto3

from io import BytesIO
from datetime import datetime, timedelta, date
from botocore.exceptions import ClientError

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

BUCKET_NAME = "afdal-idx-stock-data-s3"
DIM_STOCK_KEY = "modeled/dim_stock/data.parquet"


def upload_df_to_s3(df, bucket_name, key, s3_client=None):
    s3_client = s3_client or boto3.client("s3")
    buffer = BytesIO()
    df.to_parquet(buffer, index=False, engine="pyarrow")
    s3_client.put_object(Bucket=bucket_name, Key=key, Body=buffer.getvalue())

def init_dim_sector_industry():
    #ini untuk sementara masih di-update manual mappingannya (mengikuti kebijakan IDX) dan menggunakan SDC type 1.
    key = "modeled/dim_sector_industry/data.parquet"
    idx_ic_flat_list = [
    {
        "code": "A111",
        "sector": "Energy",
        "sub_sector": "Oil, Gas & Coal",
        "industry": "Oil & Gas",
        "sub_industry": "Oil & Gas Production & Refinery"
    },
    {
        "code": "A112",
        "sector": "Energy",
        "sub_sector": "Oil, Gas & Coal",
        "industry": "Oil & Gas",
        "sub_industry": "Oil & Gas Storage & Distribution"
    },
    {
        "code": "A121",
        "sector": "Energy",
        "sub_sector": "Oil, Gas & Coal",
        "industry": "Coal",
        "sub_industry": "Coal Production"
    },
    {
        "code": "A122",
        "sector": "Energy",
        "sub_sector": "Oil, Gas & Coal",
        "industry": "Coal",
        "sub_industry": "Coal Distribution"
    },
    {
        "code": "A131",
        "sector": "Energy",
        "sub_sector": "Oil, Gas & Coal",
        "industry": "Oil, Gas & Coal Supports",
        "sub_industry": "Oil & Gas Drilling Service"
    },
    {
        "code": "A132",
        "sector": "Energy",
        "sub_sector": "Oil, Gas & Coal",
        "industry": "Oil, Gas & Coal Supports",
        "sub_industry": "Oil, Gas & Coal Equipment & Services"
    },
    {
        "code": "A211",
        "sector": "Energy",
        "sub_sector": "Alternative Energy",
        "industry": "Alternative Energy Equipment",
        "sub_industry": "Alternative Energy Equipment"
    },
    {
        "code": "A221",
        "sector": "Energy",
        "sub_sector": "Alternative Energy",
        "industry": "Alternative Fuels",
        "sub_industry": "Alternative Fuels"
    },
    {
        "code": "B111",
        "sector": "Basic Materials",
        "sub_sector": "Basic Materials",
        "industry": "Chemicals",
        "sub_industry": "Basic Chemicals"
    },
    {
        "code": "B112",
        "sector": "Basic Materials",
        "sub_sector": "Basic Materials",
        "industry": "Chemicals",
        "sub_industry": "Agricultural Chemicals"
    },
    {
        "code": "B113",
        "sector": "Basic Materials",
        "sub_sector": "Basic Materials",
        "industry": "Chemicals",
        "sub_industry": "Specialty Chemicals"
    },
    {
        "code": "B121",
        "sector": "Basic Materials",
        "sub_sector": "Basic Materials",
        "industry": "Construction Materials",
        "sub_industry": "Construction Materials"
    },
    {
        "code": "B131",
        "sector": "Basic Materials",
        "sub_sector": "Basic Materials",
        "industry": "Containers & Packaging",
        "sub_industry": "Containers & Packaging"
    },
    {
        "code": "B141",
        "sector": "Basic Materials",
        "sub_sector": "Basic Materials",
        "industry": "Metals & Minerals",
        "sub_industry": "Aluminum"
    },
    {
        "code": "B142",
        "sector": "Basic Materials",
        "sub_sector": "Basic Materials",
        "industry": "Metals & Minerals",
        "sub_industry": "Cooper"
    },
    {
        "code": "B143",
        "sector": "Basic Materials",
        "sub_sector": "Basic Materials",
        "industry": "Metals & Minerals",
        "sub_industry": "Gold"
    },
    {
        "code": "B144",
        "sector": "Basic Materials",
        "sub_sector": "Basic Materials",
        "industry": "Metals & Minerals",
        "sub_industry": "Iron & Steel"
    },
    {
        "code": "B145",
        "sector": "Basic Materials",
        "sub_sector": "Basic Materials",
        "industry": "Metals & Minerals",
        "sub_industry": "Precious Metals & Minerals"
    },
    {
        "code": "B146",
        "sector": "Basic Materials",
        "sub_sector": "Basic Materials",
        "industry": "Metals & Minerals",
        "sub_industry": "Diversified Metals & Minerals"
    },
    {
        "code": "B147",
        "sector": "Basic Materials",
        "sub_sector": "Basic Materials",
        "industry": "Metals & Minerals",
        "sub_industry": "Mining Equipment & Services"
    },
    {
        "code": "B151",
        "sector": "Basic Materials",
        "sub_sector": "Basic Materials",
        "industry": "Forestry & Paper",
        "sub_industry": "Timber"
    },
    {
        "code": "B152",
        "sector": "Basic Materials",
        "sub_sector": "Basic Materials",
        "industry": "Forestry & Paper",
        "sub_industry": "Paper"
    },
    {
        "code": "B153",
        "sector": "Basic Materials",
        "sub_sector": "Basic Materials",
        "industry": "Forestry & Paper",
        "sub_industry": "Diversified Forest Products"
    },
    {
        "code": "C111",
        "sector": "industryals",
        "sub_sector": "industryal Goods",
        "industry": "Aerospace & Defense",
        "sub_industry": "Aerospace & Defense"
    },
    {
        "code": "C121",
        "sector": "industryals",
        "sub_sector": "industryal Goods",
        "industry": "Building Products & Fixtures",
        "sub_industry": "Building Products & Fixtures"
    },
    {
        "code": "C131",
        "sector": "industryals",
        "sub_sector": "industryal Goods",
        "industry": "Electrical",
        "sub_industry": "Electrical Components & Equipment"
    },
    {
        "code": "C132",
        "sector": "industryals",
        "sub_sector": "industryal Goods",
        "industry": "Electrical",
        "sub_industry": "Heavy Electrical Equipment"
    },
    {
        "code": "C141",
        "sector": "industryals",
        "sub_sector": "industryal Goods",
        "industry": "Machinery",
        "sub_industry": "Construction Machinery & Heavy Vehicles"
    },
    {
        "code": "C142",
        "sector": "industryals",
        "sub_sector": "industryal Goods",
        "industry": "Machinery",
        "sub_industry": "Agricultural & Farm Machinery"
    },
    {
        "code": "C143",
        "sector": "industryals",
        "sub_sector": "industryal Goods",
        "industry": "Machinery",
        "sub_industry": "industryal Machinery & Components"
    },
    {
        "code": "C211",
        "sector": "industryals",
        "sub_sector": "industryal Services",
        "industry": "Diversified industryal Trading",
        "sub_industry": "Diversified industryal Trading"
    },
    {
        "code": "C221",
        "sector": "industryals",
        "sub_sector": "industryal Services",
        "industry": "Commercial Services",
        "sub_industry": "Commercial Printing"
    },
    {
        "code": "C222",
        "sector": "industryals",
        "sub_sector": "industryal Services",
        "industry": "Commercial Services",
        "sub_industry": "Environmental & Facilities Services"
    },
    {
        "code": "C223",
        "sector": "industryals",
        "sub_sector": "industryal Services",
        "industry": "Commercial Services",
        "sub_industry": "Office Supplies"
    },
    {
        "code": "C224",
        "sector": "industryals",
        "sub_sector": "industryal Services",
        "industry": "Commercial Services",
        "sub_industry": "Business Support Services"
    },
    {
        "code": "C231",
        "sector": "industryals",
        "sub_sector": "industryal Services",
        "industry": "Professional Services",
        "sub_industry": "Human Resource & Employment Services"
    },
    {
        "code": "C232",
        "sector": "industryals",
        "sub_sector": "industryal Services",
        "industry": "Professional Services",
        "sub_industry": "Research & Consulting Services"
    },
    {
        "code": "C311",
        "sector": "industryals",
        "sub_sector": "Multi-sector Holdings",
        "industry": "Multi-sector Holdings",
        "sub_industry": "Multi-sector Holdings"
    },
    {
        "code": "D111",
        "sector": "Consumer Non-Cyclicals",
        "sub_sector": "Food & Staples Retailing",
        "industry": "Food & Staples Retailing",
        "sub_industry": "Drug Retail & Distributors"
    },
    {
        "code": "D112",
        "sector": "Consumer Non-Cyclicals",
        "sub_sector": "Food & Staples Retailing",
        "industry": "Food & Staples Retailing",
        "sub_industry": "Food Retail & Distributors"
    },
    {
        "code": "D113",
        "sector": "Consumer Non-Cyclicals",
        "sub_sector": "Food & Staples Retailing",
        "industry": "Food & Staples Retailing",
        "sub_industry": "Supermarkets & Convenience Store"
    },
    {
        "code": "D211",
        "sector": "Consumer Non-Cyclicals",
        "sub_sector": "Food & Beverage",
        "industry": "Beverages",
        "sub_industry": "Liquors"
    },
    {
        "code": "D212",
        "sector": "Consumer Non-Cyclicals",
        "sub_sector": "Food & Beverage",
        "industry": "Beverages",
        "sub_industry": "Soft Drinks"
    },
    {
        "code": "D221",
        "sector": "Consumer Non-Cyclicals",
        "sub_sector": "Food & Beverage",
        "industry": "Processed Foods",
        "sub_industry": "Dairy Products"
    },
    {
        "code": "D222",
        "sector": "Consumer Non-Cyclicals",
        "sub_sector": "Food & Beverage",
        "industry": "Processed Foods",
        "sub_industry": "Processed Foods"
    },
    {
        "code": "D231",
        "sector": "Consumer Non-Cyclicals",
        "sub_sector": "Food & Beverage",
        "industry": "Agricultural Products",
        "sub_industry": "Fish, Meat, & Poultry"
    },
    {
        "code": "D232",
        "sector": "Consumer Non-Cyclicals",
        "sub_sector": "Food & Beverage",
        "industry": "Agricultural Products",
        "sub_industry": "Plantations & Crops"
    },
    {
        "code": "D311",
        "sector": "Consumer Non-Cyclicals",
        "sub_sector": "Tobacco",
        "industry": "Tobacco",
        "sub_industry": "Tobacco"
    },
    {
        "code": "D411",
        "sector": "Consumer Non-Cyclicals",
        "sub_sector": "Nondurable Household Products",
        "industry": "Household Products",
        "sub_industry": "Household Products"
    },
    {
        "code": "D421",
        "sector": "Consumer Non-Cyclicals",
        "sub_sector": "Nondurable Household Products",
        "industry": "Personal Care Products",
        "sub_industry": "Personal Care Products"
    },
    {
        "code": "E111",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Automobiles & Components",
        "industry": "Auto Components",
        "sub_industry": "Auto Parts & Equipment"
    },
    {
        "code": "E112",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Automobiles & Components",
        "industry": "Auto Components",
        "sub_industry": "Tires"
    },
    {
        "code": "E121",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Automobiles & Components",
        "industry": "Automobiles",
        "sub_industry": "Car Manufacturers"
    },
    {
        "code": "E122",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Automobiles & Components",
        "industry": "Automobiles",
        "sub_industry": "Motorcycle Manufacturers"
    },
    {
        "code": "E211",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Household Goods",
        "industry": "Household Goods",
        "sub_industry": "Home Furnishings"
    },
    {
        "code": "E212",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Household Goods",
        "industry": "Household Goods",
        "sub_industry": "Household Appliances"
    },
    {
        "code": "E213",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Household Goods",
        "industry": "Household Goods",
        "sub_industry": "Housewares & Specialties"
    },
    {
        "code": "E311",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Leisure Goods",
        "industry": "Consumer Electronics",
        "sub_industry": "Consumer Electronics"
    },
    {
        "code": "E321",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Leisure Goods",
        "industry": "Sport Equipment & Hobbies Goods",
        "sub_industry": "Sport Equipment & Hobbies Goods"
    },
    {
        "code": "E411",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Apparel & Luxury Goods",
        "industry": "Apparel & Luxury Goods",
        "sub_industry": "Clothing, Accessories & Bags"
    },
    {
        "code": "E412",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Apparel & Luxury Goods",
        "industry": "Apparel & Luxury Goods",
        "sub_industry": "Footwear"
    },
    {
        "code": "E413",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Apparel & Luxury Goods",
        "industry": "Apparel & Luxury Goods",
        "sub_industry": "Textiles"
    },
    {
        "code": "E511",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Consumer Services",
        "industry": "Tourism & Recreation",
        "sub_industry": "Gaming Venue"
    },
    {
        "code": "E512",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Consumer Services",
        "industry": "Tourism & Recreation",
        "sub_industry": "Hotels, Resorts & Cruise Lines"
    },
    {
        "code": "E513",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Consumer Services",
        "industry": "Tourism & Recreation",
        "sub_industry": "Travel Agencies"
    },
    {
        "code": "E514",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Consumer Services",
        "industry": "Tourism & Recreation",
        "sub_industry": "Recreational & Sports Facilities"
    },
    {
        "code": "E515",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Consumer Services",
        "industry": "Tourism & Recreation",
        "sub_industry": "Restaurants"
    },
    {
        "code": "E521",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Consumer Services",
        "industry": "Education & Support Services",
        "sub_industry": "Education Services"
    },
    {
        "code": "E522",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Consumer Services",
        "industry": "Education & Support Services",
        "sub_industry": "Consumer Support Services"
    },
    {
        "code": "E611",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Media & Entertainment",
        "industry": "Media",
        "sub_industry": "Advertising"
    },
    {
        "code": "E612",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Media & Entertainment",
        "industry": "Media",
        "sub_industry": "Broadcasting"
    },
    {
        "code": "E613",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Media & Entertainment",
        "industry": "Media",
        "sub_industry": "Cable & Satellite"
    },
    {
        "code": "E614",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Media & Entertainment",
        "industry": "Media",
        "sub_industry": "Consumer Publishing"
    },
    {
        "code": "E621",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Media & Entertainment",
        "industry": "Entertainment & Movie Production",
        "sub_industry": "Entertainment & Movie Production"
    },
    {
        "code": "E711",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Retailing",
        "industry": "Consumer Distributors",
        "sub_industry": "Consumer Distributors"
    },
    {
        "code": "E721",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Retailing",
        "industry": "Internet & Homeshop Retail",
        "sub_industry": "Internet & Homeshop Retail"
    },
    {
        "code": "E731",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Retailing",
        "industry": "Department Stores",
        "sub_industry": "Department Stores"
    },
    {
        "code": "E741",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Retailing",
        "industry": "Specialty Retail",
        "sub_industry": "Apparel & Textile Retail"
    },
    {
        "code": "E742",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Retailing",
        "industry": "Specialty Retail",
        "sub_industry": "Electronics Retail"
    },
    {
        "code": "E743",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Retailing",
        "industry": "Specialty Retail",
        "sub_industry": "Home Improvement Retail"
    },
    {
        "code": "E744",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Retailing",
        "industry": "Specialty Retail",
        "sub_industry": "Specialty Stores"
    },
    {
        "code": "E745",
        "sector": "Consumer Cyclicals",
        "sub_sector": "Retailing",
        "industry": "Specialty Retail",
        "sub_industry": "Automotive Retail"
    },
    {
        "code": "F111",
        "sector": "Healthcare",
        "sub_sector": "Healthcare Equipment & Providers",
        "industry": "Healthcare Equipment & Supplies",
        "sub_industry": "Healthcare Equipment"
    },
    {
        "code": "F112",
        "sector": "Healthcare",
        "sub_sector": "Healthcare Equipment & Providers",
        "industry": "Healthcare Equipment & Supplies",
        "sub_industry": "Healthcare Supplies & Distributions"
    },
    {
        "code": "F121",
        "sector": "Healthcare",
        "sub_sector": "Healthcare Equipment & Providers",
        "industry": "Healthcare Providers",
        "sub_industry": "Healthcare Providers"
    },
    {
        "code": "F211",
        "sector": "Healthcare",
        "sub_sector": "Pharmaceuticals & Health Care Research",
        "industry": "Pharmaceuticals",
        "sub_industry": "Pharmaceuticals"
    },
    {
        "code": "F221",
        "sector": "Healthcare",
        "sub_sector": "Pharmaceuticals & Health Care Research",
        "industry": "Healthcare Research",
        "sub_industry": "Healthcare Research"
    },
    {
        "code": "G111",
        "sector": "Financials",
        "sub_sector": "Banks",
        "industry": "Banks",
        "sub_industry": "Banks"
    },
    {
        "code": "G211",
        "sector": "Financials",
        "sub_sector": "Financing Service",
        "industry": "Consumer Financing",
        "sub_industry": "Consumer Financing"
    },
    {
        "code": "G221",
        "sector": "Financials",
        "sub_sector": "Financing Service",
        "industry": "Business Financing",
        "sub_industry": "Venture Capital"
    },
    {
        "code": "G222",
        "sector": "Financials",
        "sub_sector": "Financing Service",
        "industry": "Business Financing",
        "sub_industry": "Specialize Business Financing"
    },
    {
        "code": "G311",
        "sector": "Financials",
        "sub_sector": "Investment Service",
        "industry": "Investment Services",
        "sub_industry": "Investment Management"
    },
    {
        "code": "G312",
        "sector": "Financials",
        "sub_sector": "Investment Service",
        "industry": "Investment Services",
        "sub_industry": "Investment Banking & Brokerage Services"
    },
    {
        "code": "G313",
        "sector": "Financials",
        "sub_sector": "Investment Service",
        "industry": "Investment Services",
        "sub_industry": "Market Operators"
    },
    {
        "code": "G314",
        "sector": "Financials",
        "sub_sector": "Investment Service",
        "industry": "Investment Services",
        "sub_industry": "Investment Support Service"
    },
    {
        "code": "G411",
        "sector": "Financials",
        "sub_sector": "Insurance",
        "industry": "Insurance",
        "sub_industry": "Insurance Brokers"
    },
    {
        "code": "G412",
        "sector": "Financials",
        "sub_sector": "Insurance",
        "industry": "Insurance",
        "sub_industry": "General Insurance"
    },
    {
        "code": "G413",
        "sector": "Financials",
        "sub_sector": "Insurance",
        "industry": "Insurance",
        "sub_industry": "Life Insurance"
    },
    {
        "code": "G414",
        "sector": "Financials",
        "sub_sector": "Insurance",
        "industry": "Insurance",
        "sub_industry": "Reinsurance"
    },
    {
        "code": "G511",
        "sector": "Financials",
        "sub_sector": "Holding & Investment Companies",
        "industry": "Holding & Investment Companies",
        "sub_industry": "Financial Holdings"
    },
    {
        "code": "G512",
        "sector": "Financials",
        "sub_sector": "Holding & Investment Companies",
        "industry": "Holding & Investment Companies",
        "sub_industry": "Investment Companies"
    },
    {
        "code": "H111",
        "sector": "Properties & Real Estate",
        "sub_sector": "Properties & Real Estate",
        "industry": "Real Estate Management & Development",
        "sub_industry": "Real Estate Development & Management"
    },
    {
        "code": "H112",
        "sector": "Properties & Real Estate",
        "sub_sector": "Properties & Real Estate",
        "industry": "Real Estate Management & Development",
        "sub_industry": "Real Estate Services"
    },
    {
        "code": "I111",
        "sector": "Technology",
        "sub_sector": "Software & IT Services",
        "industry": "Online Applications & Services",
        "sub_industry": "Online Applications & Services"
    },
    {
        "code": "I121",
        "sector": "Technology",
        "sub_sector": "Software & IT Services",
        "industry": "IT Services & Consulting",
        "sub_industry": "IT Services & Consulting"
    },
    {
        "code": "I131",
        "sector": "Technology",
        "sub_sector": "Software & IT Services",
        "industry": "Software",
        "sub_industry": "Software"
    },
    {
        "code": "I211",
        "sector": "Technology",
        "sub_sector": "Technology Hardware & Equipment",
        "industry": "Networking Equipment",
        "sub_industry": "Networking Equipment"
    },
    {
        "code": "I221",
        "sector": "Technology",
        "sub_sector": "Technology Hardware & Equipment",
        "industry": "Computer Hardware",
        "sub_industry": "Computer Hardware"
    },
    {
        "code": "I231",
        "sector": "Technology",
        "sub_sector": "Technology Hardware & Equipment",
        "industry": "Electronic Equipment, Instruments & Components",
        "sub_industry": "Electronic Equipment & Instruments"
    },
    {
        "code": "I232",
        "sector": "Technology",
        "sub_sector": "Technology Hardware & Equipment",
        "industry": "Electronic Equipment, Instruments & Components",
        "sub_industry": "Electronic Components & Semiconductors"
    },
    {
        "code": "J111",
        "sector": "Infrastructures",
        "sub_sector": "Transportation Infrastructure",
        "industry": "Transport Infrastructure Operator",
        "sub_industry": "Airport Operators"
    },
    {
        "code": "J112",
        "sector": "Infrastructures",
        "sub_sector": "Transportation Infrastructure",
        "industry": "Transport Infrastructure Operator",
        "sub_industry": "Highways & Railtracks"
    },
    {
        "code": "J113",
        "sector": "Infrastructures",
        "sub_sector": "Transportation Infrastructure",
        "industry": "Transport Infrastructure Operator",
        "sub_industry": "Marine Ports & Services"
    },
    {
        "code": "J211",
        "sector": "Infrastructures",
        "sub_sector": "Heavy Constructions & Civil Engineering",
        "industry": "Heavy Constructions & Civil Engineering",
        "sub_industry": "Heavy Constructions & Civil Engineering"
    },
    {
        "code": "J311",
        "sector": "Infrastructures",
        "sub_sector": "Telecommunication",
        "industry": "Telecommunication Service",
        "sub_industry": "Wired Telecommunication Service"
    },
    {
        "code": "J312",
        "sector": "Infrastructures",
        "sub_sector": "Telecommunication",
        "industry": "Telecommunication Service",
        "sub_industry": "Integrated Telecommunication Service"
    },
    {
        "code": "J321",
        "sector": "Infrastructures",
        "sub_sector": "Telecommunication",
        "industry": "Wireless Telecommunication Services",
        "sub_industry": "Wireless Telecommunication Services"
    },
    {
        "code": "J411",
        "sector": "Infrastructures",
        "sub_sector": "Utilities",
        "industry": "Electric Utilities",
        "sub_industry": "Electric Utilities"
    },
    {
        "code": "J421",
        "sector": "Infrastructures",
        "sub_sector": "Utilities",
        "industry": "Gas Utilities",
        "sub_industry": "Gas Utilities"
    },
    {
        "code": "J431",
        "sector": "Infrastructures",
        "sub_sector": "Utilities",
        "industry": "Water Utilities",
        "sub_industry": "Water Utilities"
    },
    {
        "code": "K111",
        "sector": "Transportation & Logistic",
        "sub_sector": "Transportation",
        "industry": "Airlines",
        "sub_industry": "Airlines"
    },
    {
        "code": "K121",
        "sector": "Transportation & Logistic",
        "sub_sector": "Transportation",
        "industry": "Passenger Marine Transportation",
        "sub_industry": "Passenger Marine Transportation"
    },
    {
        "code": "K131",
        "sector": "Transportation & Logistic",
        "sub_sector": "Transportation",
        "industry": "Passenger Land Transportation",
        "sub_industry": "Rail"
    },
    {
        "code": "K132",
        "sector": "Transportation & Logistic",
        "sub_sector": "Transportation",
        "industry": "Passenger Land Transportation",
        "sub_industry": "Road Transportation"
    },
    {
        "code": "K211",
        "sector": "Transportation & Logistic",
        "sub_sector": "Logistics & Deliveries",
        "industry": "Logistics & Deliveries",
        "sub_industry": "Logistics & Deliveries"
    },
    {
        "code": "Z111",
        "sector": "Listed Investment Product",
        "sub_sector": "Investment Trusts",
        "industry": "Investment Trusts",
        "sub_industry": "Mutual Fund/ETFS"
    },
    {
        "code": "Z112",
        "sector": "Listed Investment Product",
        "sub_sector": "Investment Trusts",
        "industry": "Investment Trusts",
        "sub_industry": "Real Estate Investment Trusts"
    },
    {
        "code": "Z113",
        "sector": "Listed Investment Product",
        "sub_sector": "Investment Trusts",
        "industry": "Investment Trusts",
        "sub_industry": "Infrastructure Investment Trusts"
    },
    {
        "code": "Z211",
        "sector": "Listed Investment Product",
        "sub_sector": "Bonds",
        "industry": "Bonds",
        "sub_industry": "Government Bonds"
    },
    {
        "code": "Z212",
        "sector": "Listed Investment Product",
        "sub_sector": "Bonds",
        "industry": "Bonds",
        "sub_industry": "Corporate Bonds"
    }
]
    df_sector_industry = pd.DataFrame(idx_ic_flat_list)
    upload_df_to_s3(df_sector_industry,BUCKET_NAME,key)

def init_dim_date():
    # Rentangnya bisa disesuaikan, dan cukup sekali diinitial load aja.
    start_date = "2020-01-01"
    end_date = "2040-12-31"
    date_range = pd.date_range(start=start_date, end=end_date)

    dim_date = pd.DataFrame({"Date": date_range})

    dim_date["date_key"] = dim_date["Date"].dt.strftime("%Y%m%d").astype(int)
    dim_date["date"] = dim_date["Date"].dt.date
    dim_date["year"] = dim_date["Date"].dt.year
    dim_date["month"] = dim_date["Date"].dt.month
    dim_date["quarter"] = dim_date["Date"].dt.quarter
    dim_date["day_name"] = dim_date["Date"].dt.day_name()

    dim_date = dim_date.drop(columns=["Date"])

    key = "modeled/dim_date/data.parquet"
    upload_df_to_s3(dim_date, BUCKET_NAME, key)

def _get_duckdb_connection():
    con = duckdb.connect()
    con.execute("INSTALL httpfs;")
    con.execute("LOAD httpfs;")
    con.execute("""
        CREATE OR REPLACE SECRET (
            TYPE S3,
            PROVIDER credential_chain
        );
    """)
    return con

def init_dim_stock():
    # One-time init: bangun dim_stock SCD2 dari seluruh histori curated (2020 s.d. bulan terakhir yang sudah tercompact)
    con = _get_duckdb_connection()
    source = f"s3://{BUCKET_NAME}/curated/idx/year=*/month=*/data.parquet"

    dim_stock = con.execute(
        f"""
        WITH changes AS (
            SELECT
                trade_date,
                stock_code,
                stock_name,
                COALESCE(
                    stock_name != LAG(stock_name) OVER (
                        PARTITION BY stock_code ORDER BY trade_date
                    ),
                    TRUE
                ) AS name_changed
            FROM read_parquet('{source}', hive_partitioning = true)
--            WHERE year >= 2020
--              AND (year < 2026 OR (year = 2026 AND CAST(month AS INTEGER) <= 7))
        ), last_date AS (
            SELECT MAX(trade_date) as last_update_date
            FROM changes
        ),
        versions AS (
            SELECT *,
                SUM(CAST(name_changed AS INTEGER)) OVER (
                    PARTITION BY stock_code ORDER BY trade_date
                    ROWS UNBOUNDED PRECEDING
                ) AS version
            FROM changes
        ),
        history AS (
            SELECT
                stock_code,
                version,
                FIRST(stock_name ORDER BY trade_date) AS stock_name,
                MIN(trade_date) AS valid_from,
                MAX(trade_date) AS valid_to
            FROM versions
            GROUP BY stock_code, version
        )
        SELECT
            stock_code,
            stock_name,
            valid_from,
            CASE
                WHEN ROW_NUMBER() OVER (PARTITION BY stock_code ORDER BY valid_from DESC) = 1
                THEN NULL ELSE valid_to
            END AS valid_to,
            (ROW_NUMBER() OVER (PARTITION BY stock_code ORDER BY valid_from DESC) = 1)::INTEGER AS is_active,
            (SELECT *
            FROM last_date
            ) as last_update_date
        FROM history
        ORDER BY stock_code, valid_from
        """
    ).df()

    logger.info(
        f"init_dim_stock: generated {len(dim_stock)} rows for "
        f"{dim_stock['stock_code'].nunique()} stocks"
    )
    upload_df_to_s3(dim_stock, BUCKET_NAME, DIM_STOCK_KEY)

def update_dim_stock(key):
    # SCD2 incremental update dim_stock
    con = _get_duckdb_connection()
    dim_stock_path = f"s3://{BUCKET_NAME}/{DIM_STOCK_KEY}"
    new_data_path = ", ".join(f"'s3://{BUCKET_NAME}/{path}'" for path in key)
    # new_data_path = (
    #     f"s3://{BUCKET_NAME}/{key}"
    # )

    df_stock = con.execute(
        f"""
        WITH dim_current AS (
            SELECT * FROM read_parquet('{dim_stock_path}')
        ),
        current_active AS (
            SELECT stock_code, stock_name AS current_name, valid_from AS current_valid_from, last_update_date
            FROM dim_current
            WHERE is_active = 1
        ),
        get_last_update AS (
            SELECT MAX(last_update_date) as last_update_date
            FROM current_active
        ),
        new_changes AS (
            SELECT
                trade_date,
                stock_code,
                stock_name,
                COALESCE(
                    stock_name != LAG(stock_name) OVER (
                        PARTITION BY stock_code ORDER BY trade_date
                    ),
                    TRUE
                ) AS name_changed
            FROM read_parquet([{new_data_path}], union_by_name = True)
            WHERE trade_date>(SELECT * FROM get_last_update)
        ),
        new_versions AS (
            SELECT *,
                SUM(CAST(name_changed AS INTEGER)) OVER (
                    PARTITION BY stock_code ORDER BY trade_date
                    ROWS UNBOUNDED PRECEDING
                ) AS version
            FROM new_changes
        ),
        new_segments AS (
            SELECT
                stock_code,
                version,
                FIRST(stock_name ORDER BY trade_date) AS stock_name,
                MIN(trade_date) AS seg_start,
                MAX(trade_date) AS seg_end,
                MAX(version) OVER (PARTITION BY stock_code) AS max_version
            FROM new_versions
            GROUP BY stock_code, version
        ),
        merged AS (
            -- segmen pertama tiap stock di batch baru, digabung sama record aktif eksisting
            SELECT
                s.stock_code,
                s.stock_name,
                CASE WHEN s.stock_name = c.current_name THEN c.current_valid_from ELSE s.seg_start END AS valid_from,
                CASE WHEN s.version = s.max_version THEN NULL ELSE s.seg_end END AS valid_to
            FROM new_segments s
            LEFT JOIN current_active c ON s.stock_code = c.stock_code
            WHERE s.version = 1

            UNION ALL

            -- ganti nama yang kejadian di tengah2 batch baru
            SELECT
                s.stock_code,
                s.stock_name,
                s.seg_start AS valid_from,
                CASE WHEN s.version = s.max_version THEN NULL ELSE s.seg_end END AS valid_to
            FROM new_segments s
            WHERE s.version > 1

            UNION ALL

            -- tutup record aktif lama kalau nama udah beda dari H1 batch baru
            SELECT
                c.stock_code,
                c.current_name AS stock_name,
                c.current_valid_from AS valid_from,
                s.seg_start - 1 AS valid_to
            FROM new_segments s
            JOIN current_active c ON s.stock_code = c.stock_code
            WHERE s.version = 1 AND s.stock_name != c.current_name

            UNION ALL

            -- stock tanpa data baru di batch ini (suspend dll): biarin apa adanya
            SELECT
                c.stock_code,
                c.current_name AS stock_name,
                c.current_valid_from AS valid_from,
                NULL AS valid_to
            FROM current_active c
            WHERE NOT EXISTS (
                SELECT 1 FROM new_segments s WHERE s.stock_code = c.stock_code
            )
        ),
        final_active AS (
            SELECT
                stock_code,
                stock_name,
                valid_from,
                valid_to,
                (ROW_NUMBER() OVER (PARTITION BY stock_code ORDER BY valid_from DESC) = 1)::INTEGER AS is_active
            FROM merged
        )
        SELECT stock_code, stock_name, valid_from, valid_to, is_active FROM final_active
        UNION ALL
        SELECT stock_code, stock_name, valid_from, valid_to, is_active FROM dim_current WHERE is_active = 0
        ORDER BY stock_code, valid_from
        """
    ).df()
    # cek ada perubahan beneran atau engga, sebelum upload
    changed = con.execute(
        """
        SELECT COUNT(*) FROM (
            (SELECT * FROM df_stock EXCEPT 
                SELECT stock_code, stock_name, valid_from, valid_to, is_active 
                FROM read_parquet(?))
            UNION ALL
            (SELECT stock_code, stock_name, valid_from, valid_to, is_active 
            FROM read_parquet(?) 
            EXCEPT SELECT * FROM df_stock)
        )
        """,
        [dim_stock_path, dim_stock_path],
    ).fetchone()[0]

    if changed == 0:
        logger.info(f"update_dim_stock: no changes, skip upload")
        return 

    df_last_update = con.execute(
            f"""
                SELECT max(trade_date) as last_update FROM read_parquet([{new_data_path}], union_by_name = True)
            """).fetchone()[0]

    df_stock["last_update_date"] = df_last_update
    logger.info(f"update_dim_stock: {changed} row(s), uploading")
    # return df_stock
    upload_df_to_s3(df_stock, BUCKET_NAME, DIM_STOCK_KEY)

In [ ]:
import logging
from io import BytesIO
from datetime import datetime, timedelta, date

import boto3
import pandas as pd
from botocore.exceptions import ClientError

BUCKET_NAME = "afdal-idx-stock-data-s3"

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

# Mapping column
STANDARDIZE_COLUMN_MAP = {
    "IDStockSummary": "stock_summary_id",
    "Date": "trade_date",
    "StockCode": "stock_code",
    "StockName": "stock_name",
    "Remarks": "remarks",
    "DelistingDate": "delisting_date",

    "Previous": "previous_price",
    "OpenPrice": "open_price",
    "FirstTrade": "first_trade_price",
    "High": "high_price",
    "Low": "low_price",
    "Close": "close_price",
    "Change": "price_change",

    "Volume": "volume",
    "Value": "trading_value",
    "Frequency": "frequency",

    "IndexIndividual": "individual_index",

    "Offer": "offer_price",
    "OfferVolume": "offer_volume",
    "Bid": "bid_price",
    "BidVolume": "bid_volume",

    "ListedShares": "listed_shares",
    "TradebleShares": "tradeable_shares",
    "WeightForIndex": "index_weight",

    "ForeignSell": "foreign_sell",
    "ForeignBuy": "foreign_buy",

    "NonRegularVolume": "non_regular_volume",
    "NonRegularValue": "non_regular_value",
    "NonRegularFrequency": "non_regular_frequency",
}

EXPECTED_SOURCE_COLUMNS = set(STANDARDIZE_COLUMN_MAP.keys())
EXPECTED_CURATED_COLUMNS = list(STANDARDIZE_COLUMN_MAP.values())

# Data type
INTEGER_COLUMNS = [
    "stock_summary_id", "volume", "frequency", "offer_volume", "bid_volume",
    "listed_shares", "tradeable_shares", "foreign_sell", "foreign_buy",
    "non_regular_volume", "non_regular_frequency",
]

FLOAT_COLUMNS = [
    "previous_price", "open_price", "first_trade_price", "high_price", "low_price",
    "close_price", "price_change", "trading_value", "individual_index",
    "offer_price", "bid_price", "index_weight", "non_regular_value",
]

STRING_COLUMNS = ["stock_code", "stock_name", "remarks"]
DATE_COLUMNS = ["trade_date", "delisting_date"]


# S3
def read_df_from_s3(bucket_name, key, s3_client=None):
    s3_client = s3_client or boto3.client("s3")
    try:
        response = s3_client.get_object(
            Bucket=bucket_name,
            Key=key,
        )
    except ClientError as e:
        if e.response["Error"]["Code"] in ("NoSuchKey", "404"):
            return None
        raise

    return pd.read_parquet(BytesIO(response["Body"].read()))



def upload_df_to_s3(df, bucket_name, key, s3_client=None):
    s3_client = s3_client or boto3.client("s3")
    buffer = BytesIO()
    df.to_parquet(buffer, index=False, engine="pyarrow")
    s3_client.put_object(Bucket=bucket_name, Key=key, Body=buffer.getvalue())


def save_curated_to_s3(dfs:dict):
    s3_client = boto3.client("s3")
    for key,value in dfs.items():
        curated_key = key.replace("raw/", "curated/", 1)
        logger.info(f"Uploading curated: {curated_key} ({len(value)} rows)")
        upload_df_to_s3(value, BUCKET_NAME, curated_key, s3_client)


def get_month_list(start_date, end_date):
    months = set()
    current_date = start_date
    while current_date <= end_date:
        months.add(current_date.year * 100 + current_date.month)
        current_date += timedelta(days=1)
    return sorted(months)


def load_raw(start_date, end_date):
    """Load raw data for a date range and return it as one concatenated DataFrame."""
    months = get_month_list(start_date, end_date)
    s3_client = boto3.client("s3")
    dfs = {}

    for i, year_month in enumerate(months):
        month, year = year_month % 100, year_month // 100
        mm, yyyy = f"{month:02d}", f"{year:04d}"

        if i != len(months) - 1:
            key = f"raw/idx/year={yyyy}/month={mm}/data.parquet"
            logger.info(f"Loading raw: {key}")
            dfs[key] = read_df_from_s3(BUCKET_NAME, key, s3_client)
        else:
            first_date = date(year, month, 1) if len(months) > 1 else start_date
            for current_date in pd.date_range(first_date, end_date):
                current_date = current_date.date()
                key = f"raw/idx/year={yyyy}/month={mm}/daily/date={current_date}/data.parquet"
                logger.info(f"Loading raw: {key}")

                df = read_df_from_s3(BUCKET_NAME, key, s3_client)
                if df is not None:
                    dfs[key] = df
                else:
                    logger.info(f"No data found: {key}")

    logger.info(f"Loaded {len(dfs)} raw files")
    return dfs


# Validation
def validate_source_schema(dataframe):
    actual_columns = set(dataframe.columns)
    missing_columns = EXPECTED_SOURCE_COLUMNS - actual_columns
    unexpected_columns = actual_columns - EXPECTED_SOURCE_COLUMNS

    if missing_columns:
        raise ValueError(f"Source schema validation failed. Missing columns: {sorted(missing_columns)}")

    if unexpected_columns:
        logger.warning(f"Unexpected source columns detected: {sorted(unexpected_columns)}")

    logger.info("Source schema validation passed")
    return dataframe


# Rename
def rename_columns(dataframe):
    return dataframe.rename(columns=STANDARDIZE_COLUMN_MAP)


# Data type casting
def cast_numeric_column(dataframe, column, dtype):
    original = dataframe[column]
    original_null = original.isna()
    converted = pd.to_numeric(original, errors="coerce")

    conversion_error_mask = ~original_null & converted.isna()
    conversion_error_count = conversion_error_mask.sum()

    if conversion_error_count > 0:
        bad_values = original[conversion_error_mask].unique()
        raise ValueError(
            f"Datatype conversion failed for column '{column}'. "
            f"{conversion_error_count} invalid values. Examples: {bad_values[:5]}"
        )

    dataframe[column] = converted.astype(dtype)
    return dataframe


def cast_datatypes(dataframe):
    """Apply the curated data type contract."""
    for column in INTEGER_COLUMNS:
        dataframe = cast_numeric_column(dataframe, column, "Int64")

    for column in FLOAT_COLUMNS:
        dataframe = cast_numeric_column(dataframe, column, "float64")

    for column in STRING_COLUMNS:
        dataframe[column] = dataframe[column].astype("string").str.strip()

    for column in DATE_COLUMNS:
        dataframe[column] = pd.to_datetime(dataframe[column], errors="coerce").dt.date

    logger.info("Datatype casting passed")
    return dataframe


def quality_check(dataframe):
    errors = []

    # 1. Required columns must not be null
    for column in ["trade_date", "stock_code"]:
        if dataframe[column].isna().any():
            errors.append(f"NULL found in required column '{column}': {dataframe[column].isna().sum()} rows")

    # 2. Required string values must not be empty
    empty_stock_code = dataframe["stock_code"].fillna("").str.strip().eq("")
    if empty_stock_code.any():
        errors.append(f"Empty stock_code: {empty_stock_code.sum()} rows")

    # 3. Duplicate grain
    grain_columns = ["trade_date", "stock_code"]
    duplicate_mask = dataframe.duplicated(subset=grain_columns, keep=False)
    if duplicate_mask.any():
        errors.append(f"Duplicate grain detected for ({', '.join(grain_columns)}): {duplicate_mask.sum()} rows")

    # 4. Non-negative values - IDX uses sentinels like -9999999, treat as NULL
    non_negative_columns = [
        "previous_price", "open_price", "first_trade_price", "high_price", "low_price", "close_price",
        "volume", "trading_value", "frequency",
        "offer_price", "offer_volume", "bid_price", "bid_volume",
        "listed_shares", "tradeable_shares",
        "foreign_sell", "foreign_buy",
        "non_regular_volume", "non_regular_value", "non_regular_frequency",
    ]
    for column in non_negative_columns:
        invalid_mask = dataframe[column] < 0
        if invalid_mask.any():
            logger.warning(f"Negative sentinel values in '{column}': {invalid_mask.sum()} rows. Converting to NULL.")
            dataframe.loc[invalid_mask, column] = pd.NA

    # 5. OHLC consistency (log only, not hard failures)
    ohlc_validations = {
        "High < Low": dataframe["high_price"] < dataframe["low_price"],
        "Open < Low": dataframe["open_price"] < dataframe["low_price"],
        "Open > High": dataframe["open_price"] > dataframe["high_price"],
        "Close < Low": dataframe["close_price"] < dataframe["low_price"],
        "Close > High": dataframe["close_price"] > dataframe["high_price"],
    }
    for rule, invalid_mask in ohlc_validations.items():
        if invalid_mask.sum() > 0:
            logger.warning(f"OHLC anomaly - {rule}: {invalid_mask.sum()} rows")

    # 6. Future trade date
    today = date.today()
    future_date_mask = dataframe["trade_date"] > today
    if future_date_mask.any():
        errors.append(f"trade_date in the future: {future_date_mask.sum()} rows")

    if errors:
        raise ValueError("Quality check failed:\n- " + "\n- ".join(errors))

    logger.info("Quality check passed")
    return dataframe


def transform_to_curated(dfs:dict):
    """Complete RAW -> CURATED transformation."""
    dfs_curated = {}
    logger.info("Starting RAW -> CURATED transformation")
    for key,value in dfs.items():
        dataframe = validate_source_schema(value)
        dataframe = rename_columns(dataframe)
        dataframe = dataframe[EXPECTED_CURATED_COLUMNS].copy()  # drops source-only fields (No, persen, etc.)
        dataframe = cast_datatypes(dataframe)
        dataframe = quality_check(dataframe)

        logger.info(f"Key : {key} \n RAW -> CURATED completed. Rows: {len(dataframe):,}, Columns: {len(dataframe.columns)}")
        dfs_curated[key] = dataframe
    return dfs_curated


# if __name__ == "__main__":
#     df_raw = load_raw(
#         datetime.strptime("2026-08-30", "%Y-%m-%d").date(),
#         datetime.strptime("2026-09-01", "%Y-%m-%d").date(),
#     )
#     df_curated = transform_to_curated(df_raw)
#     save_curated_to_s3(df_curated)

In [100]:
def get_month_list(start_date, end_date):
    months = set()
    current_date = start_date
    while current_date <= end_date:
        months.add(current_date.year * 100 + current_date.month)
        current_date += timedelta(days=1)
    return sorted(months)


# S3
def read_df_from_s3(bucket_name, key, s3_client=None):
    s3_client = s3_client or boto3.client("s3")
    try:
        response = s3_client.get_object(
            Bucket=bucket_name,
            Key=key,
        )
    except ClientError as e:
        if e.response["Error"]["Code"] in ("NoSuchKey", "404"):
            return None
        raise

    return pd.read_parquet(BytesIO(response["Body"].read()))


def upload_df_to_s3(df, bucket_name, key, s3_client=None):
    s3_client = s3_client or boto3.client("s3")
    buffer = BytesIO()
    df.to_parquet(buffer, index=False, engine="pyarrow")
    s3_client.put_object(Bucket=bucket_name, Key=key, Body=buffer.getvalue())


def load_curated(start_date, end_date):
    """Load curated data for a date range and return it as one concatenated DataFrame."""
    months = get_month_list(start_date, end_date)
    s3_client = boto3.client("s3")
    dfs = {}

    for i, year_month in enumerate(months):
        month, year = year_month % 100, year_month // 100
        mm, yyyy = f"{month:02d}", f"{year:04d}"

        if i != len(months) - 1:
            key = f"curated/idx/year={yyyy}/month={mm}/data.parquet"
            logger.info(f"Loading curated: {key}")
            dfs[key] = read_df_from_s3(BUCKET_NAME, key, s3_client)
        else:
            first_date = date(year, month, 1)
            for current_date in pd.date_range(first_date, end_date):
                current_date = current_date.date()
                key = f"curated/idx/year={yyyy}/month={mm}/daily/date={current_date}/data.parquet"
                logger.info(f"Loading curated: {key}")

                df = read_df_from_s3(BUCKET_NAME, key, s3_client)
                if df is not None:
                    dfs[key] = df
                else:
                    logger.info(f"No data found: {key}")

    logger.info(f"Loaded {len(dfs)} curated files")
    return dfs


def _get_duckdb_connection():
    con = duckdb.connect()
    con.execute("INSTALL httpfs;")
    con.execute("LOAD httpfs;")
    con.execute("""
        CREATE OR REPLACE SECRET (
            TYPE S3,
            PROVIDER credential_chain
        );
    """)
    return con


def fact_stock_daily(yyyy=None, mm=None, source_df=None):
    con = _get_duckdb_connection()

    if source_df is None:
        source = f"""
            read_parquet(
                's3://{BUCKET_NAME}/curated/idx/year={yyyy}/month={mm}/data.parquet'
            )
        """
    else:
        con.register("source_df", source_df)
        source = "source_df"

    return con.execute(
        f"""
        SELECT
            CAST(strftime(trade_date, '%Y%m%d') AS INTEGER) AS date_key,
            stock_code,
            regexp_extract(
                remarks,'00([A-Z][0-9]{{3}})',1
            ) AS idx_ic_code,
            previous_price,
            open_price,
            first_trade_price,
            high_price,
            low_price,
            close_price,
            price_change,
            volume,
            trading_value,
            frequency,
            foreign_buy,
            foreign_sell,
            non_regular_volume,
            non_regular_value,
            non_regular_frequency
        FROM {source}
        """
    ).df()

In [106]:
import re 

start_date = datetime.strptime("2025-01-01", "%Y-%m-%d").date()
end_date = datetime.strptime("2026-01-01", "%Y-%m-%d").date()
dfs = load_curated(start_date,end_date)
months = get_month_list(start_date,end_date)
for key,value in dfs.items():
    # months = get_month_list(start_date, end_date)
    df_daily = []
    if "daily" in key:
        df_daily.append(value)
        continue

    yyyy = re.search(r"year=(\d{4})", key).group(1)
    mm = re.search(r"month=(\d{2})", key).group(1)
    fact_key = f"modeled/fact_stock_daily/year={yyyy}/month={mm}/data.parquet"
    df = fact_stock_daily(yyyy,mm)
    upload_df_to_s3(df, BUCKET_NAME, fact_key)
    logger.info(f"Uploading: {fact_key} (DONE)")

if df_daily:
    df_daily = pd.concat(df_daily, ignore_index=True)    
    month, year = months[-1] % 100, months[-1] // 100
    mm, yyyy = f"{month:02d}", f"{year:04d}"    
    fact_key = f"modeled/fact_stock_daily/year={yyyy}/month={mm}/data.parquet"
    df = fact_stock_daily(yyyy,mm, df_daily)
    upload_df_to_s3(df, BUCKET_NAME, fact_key)
    logger.info(f"Uploading: {fact_key} (DONE)")

2026-09-18 15:54:12,624 - INFO - Loading curated: curated/idx/year=2025/month=01/data.parquet

2026-09-18 15:54:16,863 - INFO - Loading curated: curated/idx/year=2025/month=02/data.parquet
2026-09-18 15:54:19,316 - INFO - Loading curated: curated/idx/year=2025/month=03/data.parquet
2026-09-18 15:54:22,174 - INFO - Loading curated: curated/idx/year=2025/month=04/data.parquet
2026-09-18 15:54:24,103 - INFO - Loading curated: curated/idx/year=2025/month=05/data.parquet
2026-09-18 15:54:27,298 - INFO - Loading curated: curated/idx/year=2025/month=06/data.parquet
2026-09-18 15:54:29,893 - INFO - Loading curated: curated/idx/year=2025/month=07/data.parquet
2026-09-18 15:54:33,135 - INFO - Loading curated: curated/idx/year=2025/month=08/data.parquet
2026-09-18 15:54:36,278 - INFO - Loading curated: curated/idx/year=2025/month=09/data.parquet
2026-09-18 15:54:39,085 - INFO - Loading curated: curated/idx/year=2025/month=10/data.parquet
2026-09-18 15:54:42,452 - INFO - Loading curated: curated/idx/year=2025/month=11/data.parquet
2026-09-18 15:54:45,562 - INFO - Loading curated: curated/idx/year=2025/month=12/data.parquet
2026-09-18 15:54:48,142 - INFO - Loading curated: curated/idx/year=2026/month=01/daily/date=2026-01-01/data.parquet
2026-09-18 15:54:48,439 - INFO - No data found: curated/idx/year=2026/month=01/daily/date=2026-01-01/data.parquet
2026-09-18 15:54:48,442 - INFO - Loaded 12 curated files
2026-09-18 15:55:02,932 - INFO - Uploading: modeled/fact_stock_daily/year=2025/month=01/data.parquet (DONE)
2026-09-18 15:55:10,780 - INFO - Uploading: modeled/fact_stock_daily/year=2025/month=02/data.parquet (DONE)
2026-09-18 15:55:18,346 - INFO - Uploading: modeled/fact_stock_daily/year=2025/month=03/data.parquet (DONE)
2026-09-18 15:55:26,719 - INFO - Uploading: modeled/fact_stock_daily/year=2025/month=04/data.parquet (DONE)
2026-09-18 15:55:36,293 - INFO - Uploading: modeled/fact_stock_daily/year=2025/month=05/data.parquet (DONE)
2026-09-18 15:55:44,042 - INFO - Uploading: modeled/fact_stock_daily/year=2025/month=06/data.parquet (DONE)
2026-09-18 15:55:52,308 - INFO - Uploading: modeled/fact_stock_daily/year=2025/month=07/data.parquet (DONE)
2026-09-18 15:56:02,269 - INFO - Uploading: modeled/fact_stock_daily/year=2025/month=08/data.parquet (DONE)
2026-09-18 15:56:13,578 - INFO - Uploading: modeled/fact_stock_daily/year=2025/month=09/data.parquet (DONE)
2026-09-18 15:56:24,022 - INFO - Uploading: modeled/fact_stock_daily/year=2025/month=10/data.parquet (DONE)
2026-09-18 15:56:36,303 - INFO - Uploading: modeled/fact_stock_daily/year=2025/month=11/data.parquet (DONE)
2026-09-18 15:56:43,977 - INFO - Uploading: modeled/fact_stock_daily/year=2025/month=12/data.parquet (DONE)

In [20]:
def _get_duckdb_connection():
    con = duckdb.connect()
    con.execute("INSTALL httpfs;")
    con.execute("LOAD httpfs;")
    con.execute("""
        CREATE OR REPLACE SECRET (
            TYPE S3,
            PROVIDER credential_chain
        );
    """)
    return con
con = _get_duckdb_connection()

In [73]:
df_idx = con.execute(
    f""" 
    select 
        cast(strftime(d1.trade_date, '%Y%m%d') as integer) as date_key,
        d1.stock_code,
        regexp_extract(d1.remarks, '00([A-Z][0-9]{{3}})', 1) as idx_ic_code,
        open_price,
        high_price,
        low_price,
        close_price,
        volume,
        trading_value,
        frequency,
        foreign_buy,
        foreign_sell
    from read_parquet(
    's3://{BUCKET_NAME}/curated/idx/year=2026/month=08/data.parquet' 
    ) as d1
    """
).df()

In [74]:
df_idx

,date_key,stock_code,idx_ic_code,open_price,high_price,low_price,close_price,volume,trading_value,frequency,foreign_buy,foreign_sell
0,20260803,AADI,A121,9300.0,9300.0,9075.0,9100.0,4529500,4.143086e+10,3273,503600,2396100
1,20260803,AALI,D232,6900.0,7175.0,6825.0,7050.0,2232900,1.572849e+10,2078,738100,1111300
2,20260803,ABBA,E614,0.0,0.0,0.0,30.0,0,0.000000e+00,0,0,0
3,20260803,ABDA,G412,0.0,3530.0,3490.0,3500.0,10100,3.542400e+07,10,0,0
4,20260803,ABMM,A121,2550.0,2580.0,2520.0,2540.0,667500,1.699334e+09,409,197600,14600
...,...,...,...,...,...,...,...,...,...,...,...,...
18292,20260831,ZATA,E741,67.0,69.0,65.0,68.0,49491700,3.332512e+09,2902,8877000,7435000
18293,20260831,ZBRA,C311,0.0,0.0,0.0,50.0,0,0.000000e+00,0,0,0
18294,20260831,ZINC,B146,0.0,0.0,0.0,30.0,0,0.000000e+00,0,0,0
18295,20260831,ZONE,E741,0.0,780.0,700.0,770.0,82200,6.229050e+07,85,6300,0
18296,20260831,ZYRX,I221,132.0,132.0,127.0,130.0,420600,5.420150e+07,213,8100,8100

In [66]:
df_idx[df_idx["suspension_status"] == 1]["stock_code"].unique()

array(['ABBA', 'ACST', 'ADES', 'AEGS', 'AGAR', 'AKKU', 'ALMI', 'ALTO',
       'AMMS', 'ANDI', 'ARKA', 'ARMY', 'ARTI', 'ASMI', 'BAPI', 'BATA',
       'BAUT', 'BEBS', 'BEKS', 'BHIT', 'BIKA', 'BIMA', 'BLTA', 'BLTZ',
       'BMBL', 'BOSS', 'BSWD', 'BTEK', 'BTEL', 'CANI', 'CASH', 'CBMF',
       'CHIP', 'CMPP', 'CNKO', 'COAL', 'COWL', 'CPRI', 'DEAL', 'DIGI',
       'DUCK', 'DUTI', 'ELTY', 'ENVY', 'ETWA', 'EURO', 'FASW', 'FIMP',
       'FLMC', 'FOOD', 'GAMA', 'GLOB', 'GOLL', 'GRPM', 'HADE', 'HAJJ',
       'HBAT', 'HILL', 'HITS', 'HKMU', 'HOME', 'HOTL', 'HRME', 'IBFN',
       'IBOS', 'IBST', 'IDEA', 'IFSH', 'IIKP', 'IKAI', 'INAF', 'INCF',
       'INPS', 'INRU', 'INTA', 'IPAC', 'IPPE', 'IPTV', 'ISAP', 'JSKY',
       'KARW', 'KAYU', 'KBAG', 'KBRI', 'KIAS', 'KING', 'KKES', 'KLIN',
       'KOIN', 'KREN', 'LCGP', 'LFLO', 'LMAS', 'LMAX', 'LMSH', 'LOPI',
       'LUCY', 'MABA', 'MAGP', 'MANG', 'MAPB', 'MARI', 'MDRN', 'MEJA',
       'MENN', 'MFMI', 'MGLV', 'MIRA', 'MKNT', 'MLIA', 'MPPA', 'MSIE',
       'MTFN', 'MTPS', 'MTRA', 'MTSM', 'MYTX', 'NANO', 'NASA', 'NAYZ',
       'NINE', 'NUSA', 'OCAP', 'OLIV', 'PACK', 'PBRX', 'PCAR', 'PDES',
       'PGJO', 'PLAN', 'PLAS', 'PLIN', 'PMMP', 'PNGO', 'POLL', 'POLY',
       'POOL', 'POSA', 'PPGL', 'PPRO', 'PTDU', 'PTMR', 'PURA', 'PURE',
       'RAFI', 'RCCC', 'RDTX', 'RELF', 'RIMO', 'RUNS', 'SAGE', 'SBAT',
       'SCPI', 'SIMA', 'SINI', 'SKYB', 'SMCB', 'SMKM', 'SMRU', 'SOFA',
       'SONA', 'SOSS', 'SOUL', 'SPRE', 'SRIL', 'SUGI', 'SUPR', 'SWAT',
       'TAMU', 'TARA', 'TAXI', 'TDPM', 'TECH', 'TELE', 'TFCO', 'TGRA',
       'TGUK', 'TIRT', 'TOPS', 'TOYS', 'TRAM', 'TRIL', 'TRIO', 'UDNG',
       'UNIT', 'UNSP', 'URBN', 'VIVA', 'WGSH', 'WICO', 'WIDI', 'WIKA',
       'WINR', 'WMPP', 'WSBP', 'WSKT', 'ZBRA', 'ZINC', 'ALKA', 'BAJA',
       'MDIA', 'GTBO', 'BKDP', 'BIKE', 'DPNS', 'EDGE'], dtype=object)

In [67]:
df_idx[df_idx["stock_code"]=='UDNG']

,date_key,stock_code,idx_ic_code,suspension_status,open_price,high_price,low_price,close_price,volume,trading_value,...,listed_shares,tradeable_shares,index_weight,foreign_sell_1,foreign_buy_1,non_regular_volume,non_regular_value,non_regular_frequency,month,year
908,20260803,UDNG,D231,1,0.0,1175.0,1060.0,1090.0,669900,7.402115e+08,...,1750040072,1750040072,0.0,90200,48600,0,0.0,0,08,2026
1871,20260804,UDNG,D231,1,0.0,1195.0,1070.0,1195.0,844200,9.649690e+08,...,1750040072,1750040072,0.0,69200,48800,0,0.0,0,08,2026
2834,20260805,UDNG,D231,1,0.0,1290.0,1160.0,1245.0,789900,9.782145e+08,...,1750040072,1750040072,0.0,116700,25900,0,0.0,0,08,2026
3797,20260806,UDNG,D231,1,0.0,1290.0,1195.0,1250.0,874900,1.093756e+09,...,1750040072,1750040072,0.0,41400,26100,0,0.0,0,08,2026
4760,20260807,UDNG,D231,1,0.0,1375.0,1200.0,1375.0,2426100,3.264208e+09,...,1750040072,1750040072,0.0,11300,726900,0,0.0,0,08,2026
5723,20260810,UDNG,D231,1,0.0,1510.0,1340.0,1420.0,1692800,2.414888e+09,...,1750040072,1750040072,0.0,181400,162900,1000,1420000.0,1,08,2026
6686,20260811,UDNG,D231,1,0.0,1430.0,1280.0,1290.0,484600,6.414895e+08,...,1750040072,1750040072,0.0,10200,22900,0,0.0,0,08,2026
7649,20260812,UDNG,D231,1,0.0,1330.0,1180.0,1220.0,1231000,1.524133e+09,...,1750040072,1750040072,0.0,128600,47500,0,0.0,0,08,2026
8612,20260813,UDNG,D231,1,0.0,1250.0,1180.0,1200.0,439700,5.249010e+08,...,1750040072,1750040072,0.0,64700,0,0,0.0,0,08,2026
9575,20260814,UDNG,D231,1,0.0,1300.0,1170.0,1300.0,1067100,1.330499e+09,...,1750040072,1750040072,0.0,58500,40300,0,0.0,0,08,2026
10538,20260818,UDNG,D231,1,0.0,1350.0,1265.0,1315.0,808300,1.053770e+09,...,1750040072,1750040072,0.0,11500,112300,0,0.0,0,08,2026
11501,20260819,UDNG,D231,1,0.0,1380.0,1315.0,1325.0,1180500,1.593070e+09,...,1750040072,1750040072,0.0,14900,205800,0,0.0,0,08,2026
12464,20260820,UDNG,D231,1,0.0,1420.0,1250.0,1360.0,1203200,1.638078e+09,...,1750040072,1750040072,0.0,32100,358000,0,0.0,0,08,2026
13427,20260821,UDNG,D231,1,0.0,1390.0,1330.0,1345.0,305000,4.148780e+08,...,1750040072,1750040072,0.0,8600,41900,0,0.0,0,08,2026
14390,20260824,UDNG,D231,1,0.0,1360.0,1270.0,1315.0,1428800,1.883308e+09,...,1750040072,1750040072,0.0,39100,113900,0,0.0,0,08,2026
15353,20260826,UDNG,D231,1,0.0,1410.0,1270.0,1390.0,1472100,2.007692e+09,...,1750040072,1750040072,0.0,82500,285400,0,0.0,0,08,2026
16316,20260827,UDNG,D231,1,0.0,1480.0,1350.0,1445.0,2055900,2.882540e+09,...,1750040072,1750040072,0.0,41800,414100,0,0.0,0,08,2026
17279,20260828,UDNG,D231,1,0.0,1585.0,1440.0,1585.0,1794800,2.739633e+09,...,1750040072,1750040072,0.0,27100,217700,0,0.0,0,08,2026
18242,20260831,UDNG,D231,1,0.0,1740.0,1430.0,1430.0,2285500,3.418746e+09,...,1750040072,1750040072,0.0,376100,183000,0,0.0,0,08,2026

In [89]:
con.execute(
    f""" 
    select 
        *
    from read_parquet(
    's3://{BUCKET_NAME}/modeled/fact_stock_daily/year=2026/month=08/data.parquet' 
    ) as d1
    """
).df()

,date_key,stock_code,idx_ic_code,open_price,high_price,low_price,close_price,volume,trading_value,frequency,foreign_buy,foreign_sell,month,year
0,20260803,AADI,A121,9300.0,9300.0,9075.0,9100.0,4529500,4.143086e+10,3273,503600,2396100,08,2026
1,20260803,AALI,D232,6900.0,7175.0,6825.0,7050.0,2232900,1.572849e+10,2078,738100,1111300,08,2026
2,20260803,ABBA,E614,0.0,0.0,0.0,30.0,0,0.000000e+00,0,0,0,08,2026
3,20260803,ABDA,G412,0.0,3530.0,3490.0,3500.0,10100,3.542400e+07,10,0,0,08,2026
4,20260803,ABMM,A121,2550.0,2580.0,2520.0,2540.0,667500,1.699334e+09,409,197600,14600,08,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18292,20260831,ZATA,E741,67.0,69.0,65.0,68.0,49491700,3.332512e+09,2902,8877000,7435000,08,2026
18293,20260831,ZBRA,C311,0.0,0.0,0.0,50.0,0,0.000000e+00,0,0,0,08,2026
18294,20260831,ZINC,B146,0.0,0.0,0.0,30.0,0,0.000000e+00,0,0,0,08,2026
18295,20260831,ZONE,E741,0.0,780.0,700.0,770.0,82200,6.229050e+07,85,6300,0,08,2026
18296,20260831,ZYRX,I221,132.0,132.0,127.0,130.0,420600,5.420150e+07,213,8100,8100,08,2026